---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
allowVolumeExpansion: true
parameters:
  server: ${STORAGE_IP}
  share: /homelab-nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
