---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-nfs
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - hard
parameters:
  server: ${STORAGE_IP}
  share: /homelab-nfs
provisioner: nfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
