# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare
type: Opaque
stringData:
    #ENC[AES256_GCM,data:c/7ni8h5srQY/EKgHpylLZqWO5VdKDv/MVMRt3MB9+HA5A==,iv:Ku+qtBvn8L/3g3flbrW5CFn7vJvGvPN7PIKRWdu662o=,tag:/sa7eMGTfxRHj1duBDbVHQ==,type:comment]
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:DXBu5CL+xziun/6peMJwfCFVCWpV9h+75XJ6,iv:rFTpBPVE9vuOUpGWgWvMfBDFheAi4QA3xTMe0Smrj0c=,tag:lshMrAi0O1N0QEWX3Ox1nQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeXg0Qk9MUjJkRVh5MXE1
            RTNjS2M2aW1URE04TjN6Z0R6ZDIwaE9NcFhJClZuRURYVFVxV2ZFTXczeFNadFRN
            dEFQZFZ4ei9GZVdvWHY3S2JJR3JPWlUKLS0tIHQvd0dZYmdSeUc1b00xRlZ5Nisx
            V0Y3WkN0aDE1QWh0U3p6T2g3cHh6N2MKIigsVI2OKs6SwEJfiCZTk5NQXBdLJh4L
            BhLaJdwcTbCcBAj6iOC1NFGvNWGTGCKD5ff06mafxMxqktTEJoZjDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T18:27:30Z"
    mac: ENC[AES256_GCM,data:81Mu8ScyIjBKRbXErmqb0hupXAKpE6K1RD2fdyeCQ53coxG34EQMThqI0YYque2ER1gZRBc6QGLR5BcuTnvL/uohH5tiqTJHM/8enfnaguqzZP2ik+wd1sc/ejrlNAZTlEu7d8qkDFP0xL9dbSah60jrH3Cb+bG3jSI9W4qU0s0=,iv:46o/h4JYLJxSDyQqu1aJsH5Fvmb6qfISdeBM20LDZ10=,tag:1ssgyM3m22+Ibq5yBW7LYA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
