# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare
type: Opaque
data:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:6xhdj3aQ54dxIcKIzchAX1FzOvLmUl8NbVyK,iv:QOb70EMy0HzSghB0a9aBBNFBW7zeiX8ob3isr8OmFXw=,tag:92E+tZWQZ6CCIy70fHG/mw==,type:str] #ENC[AES256_GCM,data:PwbTU43rCgrZGHiVjyb4SvqQnIpP/pX/k53Nys/7UkgW8Q==,iv:DK62wNuh8vTkDIEHRPe4slVwPpTjdVkJSaYoDpasjrk=,tag:7zzrvAGBlgHBAzIqhXBFgg==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeXg0Qk9MUjJkRVh5MXE1
            RTNjS2M2aW1URE04TjN6Z0R6ZDIwaE9NcFhJClZuRURYVFVxV2ZFTXczeFNadFRN
            dEFQZFZ4ei9GZVdvWHY3S2JJR3JPWlUKLS0tIHQvd0dZYmdSeUc1b00xRlZ5Nisx
            V0Y3WkN0aDE1QWh0U3p6T2g3cHh6N2MKIigsVI2OKs6SwEJfiCZTk5NQXBdLJh4L
            BhLaJdwcTbCcBAj6iOC1NFGvNWGTGCKD5ff06mafxMxqktTEJoZjDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T18:10:27Z"
    mac: ENC[AES256_GCM,data:g4XU4TefyY4pfcaagro8R28JFkvzWWHwBsp85wTs9MAx5rsVMCdCqt1HqJoGbQDBz4OqY/NELkm5iDkh9RwPfQPfjRelpIiKKb9fBFEnCuFCdDkA3D3FRCsxrJmkBDSDr+MAimaDOzGc82Pc2Ve27tD/q0/NS767oYpvjGEVVbw=,iv:mznnzUXUMcFwnoVXad9hMtEZlDRM4w12twu7Nmgqdfg=,tag:OfxIYLfILDnDRdlj/xdduw==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
