# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: pocketid-secrets
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Nrd+Ut7uT/INksGB4Hul1OZclBdsGfwRah/y6eor5kgOoa1vyj5f,iv:b1IQE1rtvrHZAENAaPQzZgh7mBFJfoh7m2cdsEZ09Ns=,tag:4ZekaBUJSu6F6kTU0qwBpA==,type:comment]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:YW0oLEYl13xjjvE6omN8NXbtYFioIR5ofy5a/puZeDBEyhqPTqPXOnBpbzU=,iv:xD8G5e1au5LBPxahT4X5GI7373CCmKmAux1Fas1tlzI=,tag:GFlEMzRCw4eOdQWGJHdTcA==,type:str]
    MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:WQuOfdsyMRvnm/C6IjcxINV4rTIr/mKERhI+z0CAPvgfNYwFPOis2Q==,iv:VryAVurZO4HPrpIr0WVXSd1KlLD5mzdIe2QIvQ63n0E=,tag:7pFoRdUi0rHKTelmPOHLBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T21:18:48Z"
    mac: ENC[AES256_GCM,data:OOFz2ATsOcAE41G8C0ifoIYALKniVnlIn9S2eu/OH6+TRC93Jbkfz3M2+0GdBNjyPqdaPhipB6VJLCEoyiOCWcWii+JBzs77Z2cmriF0697xyU6fkVv54MRrbTDIAhi6lJOOI10rvQz02FE63Rpq9wlKS5YBW/YiEah2bJT0/fI=,iv:sHV9JHPRLWikTiuBe0B3Rh81d2w/q7mM9fuU50iqNWs=,tag:tD9BvUyBU83xENijRUs4mA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
