# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - namespace.yaml
  - ocirepository.yaml
  - pvc.yaml
  - secret.age.enc.yaml

components:
  - ../../../components/volsync/local-nfs

configMapGenerator:
  - name: immich-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
