---
controllers:
  main:
    strategy: Recreate
    pod:
      annotations:
        reloader.stakater.com/auto: "true"
      resourceClaims:
        - name: intel-gpu
          resourceClaimName: shared-intel-gpu
    containers:
      main:
        image:
          repository: ghcr.io/immich-app/immich-server
          tag: v3.2.0@sha256:ae13784ffcfcce8f4178113eb6661602a1fd1912f3d539880b8ac0dd95fc8ac2
        env:
          DB_DATABASE_NAME:
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_DATABASE_NAME
          DB_HOSTNAME:
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_HOSTNAME
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_USERNAME
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_PASSWORD
          IMMICH_CONFIG_FILE: /config/immich-config.yaml
          IMMICH_HELMET_FILE: "true"
          IMMICH_MEDIA_LOCATION: &mediaLocation /data
          REDIS_HOSTNAME: redis
          REDIS_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password
          TZ: ${CLUSTER_TIMEZONE}
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 2Gi
          claims:
            - name: intel-gpu
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1004
    runAsGroup: 1004
    fsGroup: 1004
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile: { type: RuntimeDefault }
  nodeSelector:
    feature.node.kubernetes.io/pci-0300_8086.present: "true"  # 0300 = Graphics Class, 8086 = Intel Vendor ID

immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: immich-library

machine-learning:
  enabled: false

persistence:
  config:
    type: secret
    name: immich-secret
    globalMounts:
      - path: /config/immich-config.yaml
        subPath: immich-config.yaml
        readOnly: true
  tmp:
    type: emptyDir
    globalMounts:
      - path: /tmp

route:
  immich-server:
    hostnames:
      - photos.${CLUSTER_DOMAIN}
      - photos.internal.${CLUSTER_DOMAIN}
      - photos.private.${CLUSTER_DOMAIN}
    parentRefs:
      - name: internal
        namespace: infra-gateway
      - name: private
        namespace: infra-tailscale
      - name: public
        namespace: infra-gateway
    rules:
      - backendRefs:
          - name: immich-server
            port: &port 2283

service:
  main:
    controller: main
    ports:
      http:
        port: *port

valkey:
  enabled: false
