creation_rules:
  # AGE encrypted Kubernetes secret files
  # - path_regex: kubernetes/.*/.*\.enc\.age\.ya?ml$
  - path_regex: kubernetes/.*/.*\.ya?ml$
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    age: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
  # AGE encrypted Talos configuration files
  # - path_regex: talos/.*/.*\.enc\.age\.ya?ml$
  - path_regex: talos/.*\.ya?ml$
    encrypted_regex: '((?i)(pass|secret($|[^N])|ca|crt|key|token|^data$|^stringData$|^contents$))'
    mac_only_encrypted: true
    age: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc

stores:
  yaml:
    indent: 2
