---
# Customize rules
extends: default

# Target specific files to bypass the line-length rule
rules:
  line-length:
    max: 150
    # Hier werden Dateien für diese spezifische Regel ignoriert
    ignore: |
      **/*.sops.yaml
      **/*enc.age*.yaml
      **/secrets.yaml
