---
# yaml-language-server: $schema=https://json.schemastore.org/component.json
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  # - pvc.yaml  # Inactive as main restore source is NFS - will be created manually on demand (e.g. for a s3 restore)
  - replicationdestination.yaml
  - replicationsource.yaml
  - secret.age.enc.yaml

# Patch application's PVC and add the dataSourceRef dynamically - except opted-out for backup (volsync.backube/backup=false)
patches:
  - target:
      kind: PersistentVolumeClaim
      labelSelector: volsync.backube/restore-s3=true
    patch: |
      - op: add
        path: /spec/dataSourceRef
        value:
          kind: ReplicationDestination
          apiGroup: volsync.backube
          name: ${APP}-bootstrap-s3
