---
# yaml-language-server: $schema=https://json.schemastore.org/component.json
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  # - pvc.yaml                      # Inactive as main restore source is NFS - will be created manually on demand (e.g. for a s3 restore)
  # - replicationdestination.yaml   # Inactive as main restore source is NFS - will be created manually on demand (e.g. for a s3 restore)
  - replicationsource.yaml
  - secret.age.enc.yaml
