---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-bootstrap-s3"
  labels: {}
spec:
  trigger: {}
  kopia:
    accessModes:
      - "${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"
    cacheAccessModes:
      - ${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: ${VOLSYNC_CAPACITY:=1Gi}
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=longhorn-v2}"
    capacity: "${VOLSYNC_CAPACITY:=1Gi}"
    cleanupCachePVC: false
    cleanupTempPVC: false
    copyMethod: Direct
    enableFileDeletion: true
    moverSecurityContext:
      runAsUser: ${VOLSYNC_SHARE_UID:=1003}
      runAsGroup: ${VOLSYNC_SHARE_GID:=1003}
      fsGroup: ${VOLSYNC_GID:=1003}
      fsGroupChangePolicy: "OnRootMismatch"
    repository: ${APP}-volsync-s3-secret
    sourceIdentity:
      sourceName: ${APP}-s3
    storageClassName: ${VOLSYNC_STORAGECLASS:=longhorn-v2}
