# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-s3-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:ql4RwUMdHLQIfNHvoikvSRt/gZ1Meqyg6w==,iv:CB1/+Um1+UJ8cJmdfvnCBsePNjXw6AwgLGjWPGLfQvc=,tag:F8qF4cUD7bZKlfwApuMPiw==,type:str]
    KOPIA_S3_BUCKET: ENC[AES256_GCM,data:lG9zEr6iMMp9QneBWt4=,iv:XECtdZ9P/kWQnH3ZhVi2+LfmEaBGeOqGUGYgQhqaVzg=,tag:ABv5EnpurLSG7eKjpGXVsQ==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:4I8QiM5y3vv1N/ZK+X0sJAqG4APZP8EIBQc9G1JD+hYrJMFQZRFVNLQEiP53eV29rg==,iv:SvuFeeTMI4cwqbAYTds99qu9E3renrMb/rQ2BSaiyUk=,tag:hhI8J78UpH9D0mhgLQ9/1A==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:e2a4vQc/13oh0IFNM+a/VF8FqiyM7Os/PpiYmSnQHTwyGks=,iv:zLaw+SEJAYMcpNzX1mckd3L2duhys+yIdrgvOG6p000=,tag:jV3cRLdi2Y8Wgkktc8z2Bg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aWrlhLJXEqPqzfGaLdzdnAVzbCozi1xw7NBJ9i2UQQfyhvpE8TqYGRgd,iv:lkE3acHHNXXTWwWHYvM5EdPjpPHNgWPmZ4jPabkLNAg=,tag:VpmmkytiBmzdIgJdCZdtkw==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:ZJa00bVHPdqk/syyge/QQ0ofE/5drYOhHxEv,iv:KBEwqktI1eTH3s0ItTeDNgVYiOcIbXWN83hc5L9id8s=,tag:sRbT3DcbI75I8tuKODsc4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T21:24:27Z"
    mac: ENC[AES256_GCM,data:bbl1GtnuKznIISEG+9STvylKyFJNbyDNz6epualpTQ/q86ILUbnbxigPJgcQaVvEISpfWhZQ65qiCJQHjAvoniokZDoftHATL1VXe9xyFFseN00k+7lOpOauQcJVe2ocjGVxfm/YZAWQG1qjd3YHNchsTdhcFSi7w6+khp97yhk=,iv:I9bgZ5PoDODtm7ZO1NgYiDgzlyEeC36HkhQc6rioTG8=,tag:zgYwmo4hgEHAZtSATbldNg==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
