---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-bootstrap"
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: ${VOLSYNC_TRIGGER_MANUAL:=} #restore-once
  kopia:
    accessModes:
      - "${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"
    cacheAccessModes:
      - ${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: ${VOLSYNC_CAPACITY:=2Gi}
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=longhorn-v2}"
    capacity: "${VOLSYNC_CAPACITY:=2Gi}"
    cleanupCachePVC: false
    cleanupTempPVC: false
    copyMethod: Direct
    enableFileDeletion: true
    moverSecurityContext:
      runAsUser: ${APP_UID:=1003}
      runAsGroup: ${APP_GID:=1003}
      fsGroup: ${APP_GID:=1003}
      fsGroupChangePolicy: "OnRootMismatch"
    moverVolumes:
      - mountPath: repository
        volumeSource:
          nfs:
            path: /volsync
            server: ${STORAGE_IP}
    repository: ${APP}-volsync-secret
    sourceIdentity:
      sourceName: ${APP}
    storageClassName: ${VOLSYNC_STORAGECLASS:=longhorn-v2}
    # volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=longhorn-v2-snapshots}
