# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
type: Opaque
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:s6P/8L5p0bISGq3/KqKR,iv:pt5751WIlG1So1iP6mPVdrSUPuYPbVtjCh6zkCGs4Es=,tag:z5MwDZm2S3L3INC+0eW27g==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:3b3q5Wax3AT/Y63uTlWpf9ZYfDjxhpzCmw==,iv:4rnlBiArcViftbXqxgN3oiZ7zY3HoEj+Z+bQNte0Ak8=,tag:ua63TXKVW+wyEGDms7o08g==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:bl+7iqh2ufcfn4cGlCeJ0mrCkO4U8CBqSGUGgQ==,iv:6BU5Z9tY+aVg+ycBA3rU7GVeWdAB0Rha/4ZurXkPfXM=,tag:JYvKMhnAKOVSEEs6DelrgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T21:08:40Z"
    mac: ENC[AES256_GCM,data:UEpyDQ0a+ylfX8tgvv1aPwRXHkHnhwb47XZto9V7IwfeRHVFum0k5WC0FYrfZG/t0DSBA35zlK1rRXiwTKtD7vSHiHcoospERtZlsRhTACZshDkObS8IhO/8XRVz157QOu1Z6idfz69fwXH81iL0VSr5XNZE3+o/UuFy5eZVTPg=,iv:DApLV2DLaSaESni+GHbcJlE6T30MTQdq0/9nooY1T70=,tag:iyGWD7N+pKM1wcr/B+Apqw==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
