apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-qnap-volsync
spec:
  capacity:
    storage: 200Gi # Size of Storage volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volsync
    server: ${STORAGE_IP}
