---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-v2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" # set as cluster default
allowVolumeExpansion: true
parameters:
  dataEngine: "v2" # Enforces the usage of the high-performance V2 Data Engine (SPDK)
  dataLocality: "best-effort" # Forces Longhorn to keep a local data copy on the same node where the Pod runs. This prevents disk reads from being choked by network latencies.
  frontend: "nvme" # Configures NVMe-oF/TCP as the reliable user-space frontend, ideal for Pi 5 kernel compatibility - ublk not supported on RPi
  fsType: "ext4"
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-static
allowVolumeExpansion: true
parameters:
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
