---
defaultSettings:
  autoDeleteWorkloadPod: true          # Force-deletes stuck pods if the Pi 5 NVMe hat suffers a momentary PCIe power drop
  defaultDataPath: /var/mnt/nvme       # set falllback path
  createDefaultDiskLabeledNodes: true  # Only use explicitly labeled nodes (kubectl label node <node> node.longhorn.io/create-default-disk=true)

  defaultReplicaCount: 3

  concurrentReplicaRebuildPerNodeLimit: 4
  concurrentVolumeBackupRestorePerNodeLimit: 1
  defaultUblkQueueDepth: 128
  defaultUblkNumberOfQueue: 4
  disableRevisionCounter: true
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  replicaAutoBalance: "best-effort"   # Automatically redistributes replicas evenly across nodes when a broken node recovers
  replicaSoftAntiAffinity: true
  guaranteedInstanceManagerCPU: 10    # amount of allocated CPU on a node for instance manager (interpreted in %)

  backupTarget: ""
  backupTargetCredentialSecret: ""

  v2DataEngine: true                  # enable V2 engine

# Reduce resource usage for Pi nodes
longhornManager:
  priorityClassName: system-cluster-critical
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
longhornDriver:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
csi:
  attacherReplicaCount: 2
  provisionerReplicaCount: 2
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

longhornUI:
  replicas: 1

httproute:
  enabled: true
  parentRefs:
    - name: internal
      namespace: infra-gateway
    - name: private
      namespace: infra-tailscale
  hostnames:
    - 'longhorn.internal.${CLUSTER_DOMAIN}'
    - 'longhorn.private.${CLUSTER_DOMAIN}'
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: longhorn-frontend
          port: 80

ingress:
  enabled: false               # setup done with dedicated httproute yaml manifest

# Default StorageClass options
persistence:
  defaultClass: false          # setup done with dedicated yaml manifest
  defaultClassReplicaCount: 3
