---
defaultSettings:
  defaultDataPath: /var/mnt/nvme       # set falllback path
  createDefaultDiskLabeledNodes: true  # Only use explicitly labeled nodes (kubectl label node <node> node.longhorn.io/create-default-disk=true)

  defaultReplicaCount: 2

  # Prevent rebuild storms  per node and optimize limits
  concurrentReplicaRebuildPerNodeLimit: 1
  concurrentVolumeBackupRestorePerNodeLimit: 1
  disableRevisionCounter: true
  replicaSoftAntiAffinity: true
  replicaAutoBalance: best-effort
  guaranteedInstanceManagerCPU: 5  # amount of allocated CPU on a node for instance manager (interpreted in %)

  backupTarget: ""
  backupTargetCredentialSecret: ""

  # enable V2 engine
  v2DataEngine: true

# Reduce resource usage for Pi nodes
longhornManager:
  priorityClassName: system-cluster-critical
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
longhornDriver:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
csi:
  attacherReplicaCount: 2
  provisionerReplicaCount: 2
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

longhornUI:
  replicas: 1

ingress:
  enabled: false              # setup done with dedicated httproute yaml manifest

# Default StorageClass options
persistence:
  defaultClass: false          # setup done with dedicated yaml manifest
  defaultClassReplicaCount: 2
