---
defaultSettings:
  autoDeleteWorkloadPod: true          # Force-deletes stuck pods if the Pi 5 NVMe hat suffers a momentary PCIe power drop
  defaultDataPath: /var/mnt/nvme       # set falllback path
  createDefaultDiskLabeledNodes: true  # Only use explicitly labeled nodes (kubectl label node <node> node.longhorn.io/create-default-disk=true)

  defaultReplicaCount: 2

  concurrentReplicaRebuildPerNodeLimit: 1   # Prevent rebuild storms  per node and optimize limits
  concurrentVolumeBackupRestorePerNodeLimit: 1
  defaultUblkQueueDepth: 64           # Resource optimization: lowers queue depth to save CPU cycles and RAM overhead
  defaultUblkNumberOfQueue: 1
  disableRevisionCounter: true
  replicaAutoBalance: "best-effort"   # Automatically redistributes replicas evenly across nodes when a broken node recovers
  replicaSoftAntiAffinity: true
  guaranteedInstanceManagerCPU: 5     # amount of allocated CPU on a node for instance manager (interpreted in %)

  backupTarget: ""
  backupTargetCredentialSecret: ""

  v2DataEngine: true                  # enable V2 engine

# Reduce resource usage for Pi nodes
longhornManager:
  priorityClassName: system-cluster-critical
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 384Mi
longhornDriver:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
csi:
  attacherReplicaCount: 2
  provisionerReplicaCount: 2
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

longhornUI:
  replicas: 1

ingress:
  enabled: false               # setup done with dedicated httproute yaml manifest

# Default StorageClass options
persistence:
  defaultClass: false          # setup done with dedicated yaml manifest
  defaultClassReplicaCount: 2
