# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: infra-flux
spec:
  path: ./kubernetes/applications/infra/storage/longhorn
  targetNamespace: infra-storage
  interval: 15m
  retryInterval: 1m
  timeout: 3m
  prune: true
  wait: true
  dependsOn:
    - name: cilium
    - name: snapshot
  sourceRef:
    kind: GitRepository
    name: homelab
  decryption:
    provider: sops
    secretRef:
      name: sops-age

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot
  namespace: infra-flux
spec:
  path: ./kubernetes/applications/infra/storage/snapshot
  targetNamespace: infra-storage
  interval: 15m
  retryInterval: 1m
  timeout: 3m
  prune: false
  wait: false
  sourceRef:
    kind: GitRepository
    name: homelab
