---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-bootstrap"
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  kopia:
    accessModes:
      - "${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"
    cacheAccessModes:
      - ${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: ${VOLSYNC_CAPACITY:=2Gi}
    cacheStorageClassName: "${VOLSYNC_STORAGECLASS:=longhorn-v2}"
    capacity: "${VOLSYNC_CAPACITY:=2Gi}"
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: Snapshot
    enableFileDeletion: true
    moverSecurityContext:
      runAsUser: ${APP_UID:=1003}
      runAsGroup: ${APP_GID:=1003}
      fsGroup: ${APP_GID:=1003}
    moverVolumes:
      - name: nfs-repository
        mountPath: /repository
        volumeSource:
          nfs:
            path: /volsync
            server: ${STORAGE_IP}
    repository: ${APP}-volsync-secret
    sourceIdentity:
      sourceName: ${APP}
    storageClassName: ${VOLSYNC_STORAGECLASS:=longhorn-v2}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=longhorn-v2-snapshots}
