# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
type: Opaque
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:mOKPpyWGH7v0r0k=,iv:2GOqvsyGSIDgtZhMYJx1UyDimvaLGPT+mdJv4UfwGLs=,tag:WXCf9ow+PqrO4BK4rxRhxg==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:1SyPG6zTQzDXktqZTodhFqXo0uT5XEVW,iv:dgAxyOF2IR0AqtFIlZO1LKOzsU4+5+BIT9v2rdBck1c=,tag:HMtVvuwcHJqYcOSTYiBbrg==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:r7N0EsvsA9Fk9BpzeB/ww993qyaXDJB3,iv:p08u6YsmGEnoEN3RPoUtjgcRCystOiFWLndjx6I046w=,tag:Zt9TV9a4z2vjMpYDKjsXhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T18:10:35Z"
    mac: ENC[AES256_GCM,data:1U9nI73LLa8yi2Tk0Qn/IOmc7ro9TQxipW0qWkK1XKNo+c9qhGDwbzSTFHaQjJfqpxcFH4GWZclnFeSCgLjykLawIhZqLKjDnJriXW6zqSEpNmJglUrq4Uot0FGkNxSGC4LQuz5kkxi9LAnI6x4xXkEKtHTm1+pCMsP9fcIk2VY=,iv:ryqMvWPW8ROwJE4jJb6s5t+NQ+S91i2tWbtibIcO3/8=,tag:t4xdUYF0KSnXUlemMv4ltA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
