# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
type: Opaque
stringData:
    KOPIA_FS_PATH: ENC[AES256_GCM,data:s6P/8L5p0bISGq3/KqKR,iv:pt5751WIlG1So1iP6mPVdrSUPuYPbVtjCh6zkCGs4Es=,tag:z5MwDZm2S3L3INC+0eW27g==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:1SyPG6zTQzDXktqZTodhFqXo0uT5XEVW,iv:dgAxyOF2IR0AqtFIlZO1LKOzsU4+5+BIT9v2rdBck1c=,tag:HMtVvuwcHJqYcOSTYiBbrg==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:bl+7iqh2ufcfn4cGlCeJ0mrCkO4U8CBqSGUGgQ==,iv:6BU5Z9tY+aVg+ycBA3rU7GVeWdAB0Rha/4ZurXkPfXM=,tag:JYvKMhnAKOVSEEs6DelrgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T20:58:49Z"
    mac: ENC[AES256_GCM,data:V6GN8TRbD49JavoXy8sNwwr5meirjTDbgB/bT2GZsVnkSAEfW1F1FUdFNAaiwRfPYkvB7WGAyb2NhTgRWA+h8zPzTTkrBdm+2qNN8Y+06dt4kkn3eoB/72rXXgs2/yhqpm3fy/zGuwhdfnInUkhaIPXX2s0eD1OIGI58nKL11EE=,iv:tB9RtKQ0PGl98CHsZ+W/dCOa9YqbHO7Ca/HIxdN/Wvg=,tag:W5FYLzZ7PRsc3DAPfD8baw==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
