# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-credentials
stringData:
  credentials.json: ENC[AES256_GCM,data:TO_BE_CREATED,...]
