# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-operator
  namespace: infra-grafana
spec:
  interval: 12h
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator
  ref:
    tag: "5.23.0"
