# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:gi/sMzA=,iv:AG6BFmsHX3V7Ub6aVZWF/xdE6/uOENih5gqOMIQzXt0=,tag:xb/1QlaWjYNdRY8uO6nzJw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:BvZfJJOi5mNHemdhyOXjAELpTJil9Hg=,iv:FqXWyO6UHVAQJEEPAy/YLpGYSPgrAV8RSarlTao5bL8=,tag:jZDWfeyAGBaf0pboSgAoKQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:c9vgQBmA0nqe8XCFVLZ/z6Pzijj7+sEfHMZTXg7F22I=,iv:s2anmrsn//KQ1QJdeKmwZJViBJy/yVFmiCxfSAX/HmQ=,tag:LMeh3cXdN1PBPcHwNMsI0Q==,type:str]
    PAPERLESS_OIDC_CONFIG: ENC[AES256_GCM,data:xC9zGNjznO4R8bwZkdCl1WYaOlbkU8r8Ue8EHC/TU52yQMTOpbJwURWqa8+vqyalRKrb0HvvEBoc4E6BPUZbkOE6Rc2OEU06GZ0hJK5rlDU4xaZ29WyizNW8Ha7/fNo9/EGyuJUu4YAN9Ti1TJIsF+GoJ3KW3lZZSxhz/H4e0ujVsAbSp1LWrs0+Y2fAGfCZsRkKL4YT3H00+SfjV/FjJUU5r9jVaXH4yzmsLPMfNAQ8qP/c42iE+YSnCCf/ZBn/FfW+IRvzPTt1gR0i9NUaMLgCNirjLFoucFCHEMD53n8XMBg2biBqmPvz5e1s2HajouWrKs9goVU/iW3a3W1Zj90QOWPQCgZLk9L86r49ApeQTjjPO2V42mfFJv4h4BQaZlafObS0rf7lcOyB2ED4oQT1HkvZ0Pj/DdLzoeqoRWs/orhtEOtprMkmDKedkWY=,iv:Nkr7j0nKMX8OM4Y4GSqrFyXoeCJ3amkwirEJdvgN0Ig=,tag:jM42VvpdWgv1zPBgL05D7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T20:31:53Z"
    mac: ENC[AES256_GCM,data:klAxKCIg2M3lFTyPZC/6h2nT3dvDKs2XCd6HvA5mRGw5/GR+BbVt7P6dWna7usJPUHkBgrLFKirYEAcYjz5ztd05WRAloNX1Poi5w08aIcpA79+aphkFbidUCf3yVsPiJhEe217BY+BRYQ8RY6uBrH40ji16tUgQcwPU+gs6nNI=,iv:zRmTPFRPH3bOUZ6EsFnJrU9pgPqwhAofav9h/hG017I=,tag:yZFXFIJbqfRYC6WfWty2aw==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
