# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:gi/sMzA=,iv:AG6BFmsHX3V7Ub6aVZWF/xdE6/uOENih5gqOMIQzXt0=,tag:xb/1QlaWjYNdRY8uO6nzJw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:BvZfJJOi5mNHemdhyOXjAELpTJil9Hg=,iv:FqXWyO6UHVAQJEEPAy/YLpGYSPgrAV8RSarlTao5bL8=,tag:jZDWfeyAGBaf0pboSgAoKQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:c9vgQBmA0nqe8XCFVLZ/z6Pzijj7+sEfHMZTXg7F22I=,iv:s2anmrsn//KQ1QJdeKmwZJViBJy/yVFmiCxfSAX/HmQ=,tag:LMeh3cXdN1PBPcHwNMsI0Q==,type:str]
    PAPERLESS_OIDC_CONFIG: ENC[AES256_GCM,data:caDQHGPAP05Xt5mYGYB/Ktce2UYrTj6Qev9IS4dMl/uXNTTyHKsPeZoLMo4lYHrzv+N22Rww1iZyMZl9F5rxMTxfkwSrnyN/z77Y16b0841TW1U8vxzlngf7FW45I+qRqx90nhfFi5lpUqu52s/HlDTuyxj+nwtPMMFjPMKZh9AP/zSetlyKSeuR2BlGnWRSy9V9IPp3tXBFYyk05F110a8zt/oINMMRMYwwdbuRBsj7/8D61+MfPEW+QIpNgsAMYx3J0FFLhz0/dzf39NDBRAuQis+blNFtQ2SRYpa1A45fKPfGU4EEzHoCPT/NRzJHHL7O6qE5pNzYdz+kjfFoU1MT5cp/27lX8G6fTVDB8Y1zKZsw6CsxvHZYQl8+9W1dI033+4RjoJCWlq31BbXvZMfMU6ccQMD3mbXp/zBcAZoAjIRNNiyGbJHk4I4Ck74=,iv:TuAJgiB3GXPbqnZkcaWemFehv1DjL4FM+LVSQqjjgcQ=,tag:SzEKk1dMOfasnWblWIGBXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T20:19:29Z"
    mac: ENC[AES256_GCM,data:DsbfYUlpbo8Zm7bm9GFr0YjoxTZuY+qqfYqiId8hBffVIgWn1IxMqtnV56hkEJq2O+wfJ/yZeJHp0Z9LjCqVxjJN7FRyxAsEnhsLrgkXAh7N/Et81YznfpvWfnDcm2yAoTD3qtTDZ9hz2wMtedO759N2r7s7JmxgNx1sGgYJ8xg=,iv:2he346Bqa+E+KqLSXMqrjHrvf/6ap5IlrQGCEDaZjOQ=,tag:W6FbtZBujgu7U5CobDB+0Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
