# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:dd2uyc7Cs9zV3vy/L+nEglcaICO7GPU=,iv:byNiWPgMOyHJqskbabbyg9/k4YqrgZWkFgfS7OmmWcA=,tag:1bwOmgahcxfg5enTNOHr0A==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:unj9HsRvWasOGoHcOB4WVqt83GNluki/YTIb,iv:gi3VLuwq9bsdF9zbp2W5LXkD9NGYoRcAF117Bcjd3bw=,tag:TG7GOSDdyqFMNtOzBP4GAg==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:c9vgQBmA0nqe8XCFVLZ/z6Pzijj7+sEfHMZTXg7F22I=,iv:s2anmrsn//KQ1QJdeKmwZJViBJy/yVFmiCxfSAX/HmQ=,tag:LMeh3cXdN1PBPcHwNMsI0Q==,type:str]
    PAPERLESS_OIDC_CONFIG: ENC[AES256_GCM,data:Min/ahmgHEez8BZvY0RU7poCzFYoYwBJUhW3ygMZMMViM5q757r0a+TpIssR14Ao2hF1Ajc+ZQe1S7U5hexLfaZLWSdWmJX5Ku+q9Bcs20Az4CroDFRnqdpA/h91alrQ5JzAikhrsoHlImTOCiX0hFv86eTUV5nid38rjU/pwSKSV0RG9vUKtom4ezdvx3uQCtLrPoHK2AxXiHRuDksASwFD457RNkEQZBSisG5b4607hn+JtfMt0MqC9cdlAVEudQMJwbD9ljw0JwKP2nxXlaIbj7JdTYlMgkgGjzTOiSio+H21G+xxPHcfqlKSHJo8UTXsgW2+PVA9ZIU1JtyyZp7fLg5059EpROz7V6ixbXwYSQyhUhR884TL7Og4BMS4XSVFpojqMfNs2uHDzH05MKVbI6EftLASHu5EpsSIU4qCHX21snp4x+qsaA3hkgLXXJ3Sj2mOuQi+,iv:NoipOVJjw6Ywk4S19aP8nc62xg9EfhTm4tOhu/kS3cE=,tag:IHDVd82w8lOCNhSg2QONmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T19:21:21Z"
    mac: ENC[AES256_GCM,data:NqGvoABY4xJkg8Aqv8VqRGlNEIMruE6PKCO7sJ6SEl3N5ko29XtIFnA7e+oihWOyHmmI/IWV2+QKqtvR9eeBcfJVcMNhWKcApQs6fuAeGil6JZBVsqTeUUyg60TjUXgj22n7JojpTlBIc5TgmIA2mCCdesQh6zVuKv4yVYw9hm8=,iv:JVwRqKOuXr5ySmPbr/adN+0TT1NvihY/ngti0YGZa3A=,tag:gxGosi8D+JojEz6VALBTWA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
