---
controllers:
  paperless:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/paperless-ngx/paperless-ngx
          tag: 2.20.15
        env:
          # Configure application
          PAPERLESS_SECRET_KEY: $(PAPERLESS_SECRET_KEY)
          PAPERLESS_ALLOWED_HOSTS: "paperless.internal.${CLUSTER_DOMAIN},paperless.private.${CLUSTER_DOMAIN}"
          PAPERLESS_CORS_ALLOWED_HOSTS: "https://paperless.internal.${CLUSTER_DOMAIN},https://paperless.private.${CLUSTER_DOMAIN}"
          PAPERLESS_CSRF_TRUSTED_ORIGINS: "https://paperless.internal.${CLUSTER_DOMAIN},https://paperless.private.${CLUSTER_DOMAIN}"
          PAPERLESS_PORT: "8000"
          PAPERLESS_TIME_ZONE: ${CLUSTER_TIMEZONE}
          PAPERLESS_WEBSERVER_WORKERS: "2"
          PAPERLESS_TASK_WORKERS: "2"
          # Configure folders
          PAPERLESS_CONSUMPTION_DIR: /data/local/incoming # /data/nas/incoming
          PAPERLESS_DATA_DIR: /data/local/data
          PAPERLESS_EXPORT_DIR: /data/local/export # /data/nas/export
          PAPERLESS_MEDIA_ROOT: /data/local/media
          # Configure folder importer
          PAPERLESS_CONSUMER_DELETE_DUPLICATES: 1
          PAPERLESS_CONSUMER_POLLING: "120"
          PAPERLESS_CONSUMER_RECURSIVE: "true"
          PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
          # Configure OCR
          PAPERLESS_OCR_LANGUAGE: deu
          PAPERLESS_OCR_LANGUAGES: "deu eng"
          PAPERLESS_OCR_MODE: skip # do not ocr if embedded text found
          PAPERLESS_OCR_SKIP_ARCHIVE_FILE: with_text # do not create archived version if embedded text found
          PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
          # Configure redis integration
          PAPERLESS_REDIS: "redis://:$(redis-password)@redis:6379"
          # Configure user
          USERMAP_GID: "100" # gladius:users
          PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "true"
          PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
          PAPERLESS_SOCIALACCOUNT_PROVIDERS: $(PAPERLESS_OIDC_CONFIG)
          # Configure admin user
          PAPERLESS_ADMIN_MAIL: "admin@${CLUSTER_DOMAIN}"
          PAPERLESS_ADMIN_USER: $(PAPERLESS_ADMIN_USER)
          PAPERLESS_ADMIN_PASSWORD: $(PAPERLESS_ADMIN_PASSWORD)
        envFrom:
          - secretRef:
              name: paperless-secret
          - secretRef:
              name: redis-secret
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            memory: 1Gi

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    retain: true
    advancedMounts:
      paperless:
        app:
          - path: /data/local
  # nas:
  #   type: nfs
  #   path: /mnt/tank/apps/paperless
  #   server: ${STORAGE_IP}
  #   advancedMounts:
  #     paperless:
  #       app:
  #         - path: /data/nas

route:
  app:
    hostnames:
      - paperless.internal.${CLUSTER_DOMAIN}
      - paperless.private.${CLUSTER_DOMAIN}
    parentRefs:
      - name: internal
        namespace: infra-gateway
      - name: private
        namespace: infra-tailscale
    rules:
      - backendRefs:
          - identifier: app
            port: http

service:
  app:
    ports:
      http:
        port: 8000
