# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:YBBmB3/U4tY0+0icLBse9vSEpIE=,iv:cvRGWb+tYrNtA4S3795ri2MGCIzk5uesyXUeJFaI1u8=,tag:HpmDl1wQxd4fLCRimGJlvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T20:46:37Z"
    mac: ENC[AES256_GCM,data:3SplGgXcNAS1QVTIGoFlFLMX9nWI/v2LzBTMkHxF67t/GcBY0BDpQowCfi2uS/zcw/MZ5Jj/8rWKgh0lkGHqDDaqsjzpH6yTslhYMe0Y2T3klZEirhDR7ao3IGfl+DoaMR3PTsRW/lpCMTt2i1BWGjqvaDKmM+YC7Twfz1mDpqk=,iv:fxzH6UcSszxuTB6bQjjb9OMtE6Oxd8CiN0iGb+CflR4=,tag:kjVgZkYIK9SoDkWzjNWQqA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
