# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: infra-prometheus
spec:
  interval: 1h
  releaseName: prometheus-operator-crds
  targetNamespace: infra-prometheus
  chart:
    spec:
      chart: prometheus-operator-crds
      sourceRef:
        kind: OCIRepository
        name: prometheus-crds
        namespace: infra-prometheus
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
