# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-secret
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:CDgk1LnJSZAoF1koyNufrdUdsRc683VcVN4FzITbkcEHoPoM,iv:39MPOvSuSi/CM4mHRgZYzxylz25T7mx7CiruaH9bX8w=,tag:0YDc9jEv1elbpad7QseKvw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:yuPQtiiC5yvTI+MK27tZlJsXWcYoFP+VuNaB4i8E0xU=,iv:CYxZ0sV5CYS7wbl/HtmB7q/42opefRW99SkrlSTQkOM=,tag:Rj1w7rfS9617evJd0d+www==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:akjA1NxHvxNYbNH565IL35jMImptxKLmmU/v48mT,iv:pu/bjuuEvimCWk3BgD1iYkcMxzL2be2qyHQxDvQJGeQ=,tag:o1tuP0hkWsdeu1W7yrwmgw==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:WXDQs4gxF2080rA9cJL6Sbw6o4M=,iv:bxV+lGuzN5FIxA789jMh//icfJa9T1jz5HH59mj9uyQ=,tag:BfqtmbvOs043ChZc9j347g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbnJ1V3ROUndONFFmbmpM
            ajY0OVBUcENHUFlPaUhXMHRDV1BPOWZKMG5JCjJTOEVqdG14akZPRzlzT0dzc0Jk
            TS9vU1ExaTAzMzNYdk1FSjJUT2hqVkkKLS0tIFYzVURlQUNoeXo3Q0ZtK0x5bEN2
            YUdycE5DVEVOa2JQWjJYamRZOFA3QVEKeoQW8yrrftaOf47nqbC8agR9uIWxIGkN
            nsseZn5dVK24yshnfgswO1KW2p4dDOfloM+n8f08FdXtEfo2IvG/KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T09:25:57Z"
    mac: ENC[AES256_GCM,data:58eX+s9aD/4ZhttRO6REqKy4GX7PFnq8gwfQu2HsKHtn40gHiz0q4sUidRVcyC027bpGqJjMylVG14RzcZCHXK9nDH7h25M5ZUF3GyhB7wga9tjH51DpcXyg3L+gjYi4Tt6PhiYQQGtZ0bmweIixQ3ZYE22+XGJuw7KNReFAENk=,iv:WKwPdIkIXSSN//FRGQELzMJ9BKIyCdyxRtnOb36gc7g=,tag:HUvc/3lGkqmiGPCl7SuuAw==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
