# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-secret
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:PEunW82yF6q8Id4v,iv:+h2QUGIfc/jpIP5rICIEzu0tSXU3HjR5I8hhKN/mLzg=,tag:jb/rVMtqjIGhDbr/VFiFZQ==,type:str] #ENC[AES256_GCM,data:rRo51V0NNNMsdVfDbgtMuuM+ekZTz8nqIRxJDImFC6y/rU0IFc6Bb6UQnwqNFA==,iv:jDBqZyv3fYZzJAXQoS4XYxermVIV/oAX7dAXffXrg0s=,tag:KnN2NMf/g4UorCq0WH1mmQ==,type:comment]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:fnSsy+EBTYtCxztsGn0jz4ExwIXGCN8RgGKfdorHvsNsB+4kHnXvG4ELGTyEBIb2pKaLO4h8e3eXuupOIY3ne7Pmotk7FL6IyGpoWZhw7W3VzjSfdZFC+U00V2YI0rdGsZkTGsDNEjEolfbbWUk8VTseI279nOlRdz4vu38cCic=,iv:qc6T5VCOIhBooME1MXUzInrPcWE/+t/0NYhKtk48R4I=,tag:sDzoYY4nsNBWJODXeBH+Ew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbnJ1V3ROUndONFFmbmpM
            ajY0OVBUcENHUFlPaUhXMHRDV1BPOWZKMG5JCjJTOEVqdG14akZPRzlzT0dzc0Jk
            TS9vU1ExaTAzMzNYdk1FSjJUT2hqVkkKLS0tIFYzVURlQUNoeXo3Q0ZtK0x5bEN2
            YUdycE5DVEVOa2JQWjJYamRZOFA3QVEKeoQW8yrrftaOf47nqbC8agR9uIWxIGkN
            nsseZn5dVK24yshnfgswO1KW2p4dDOfloM+n8f08FdXtEfo2IvG/KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T21:26:38Z"
    mac: ENC[AES256_GCM,data:LdkSjNKqpkjG3Avaaqdc+731vMIuh39CIAp0ecHyssIYULfQNf/EGkdDoldg0QzPOKcd3XdICnETSm3njjKZ4E0BZTfcQxSUAYStOwlC0dPXEk5ZCpAW4lHDkKl2hQlUHOgxGUYXaL2EJlu2IDxmR2Bz5mvWJ84c4WjHys4FufA=,iv:QpLvNyuY59yBdxZM6Tjvet7Um0OmdEkg+IGFl2Q5XuM=,tag:0v5r9ZYhxV1DyJRZBaxNew==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
