# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc-secret
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:CDgk1LnJSZAoF1koyNufrdUdsRc683VcVN4FzITbkcEHoPoM,iv:39MPOvSuSi/CM4mHRgZYzxylz25T7mx7CiruaH9bX8w=,tag:0YDc9jEv1elbpad7QseKvw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:yuPQtiiC5yvTI+MK27tZlJsXWcYoFP+VuNaB4i8E0xU=,iv:CYxZ0sV5CYS7wbl/HtmB7q/42opefRW99SkrlSTQkOM=,tag:Rj1w7rfS9617evJd0d+www==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:akjA1NxHvxNYbNH565IL35jMImptxKLmmU/v48mT,iv:pu/bjuuEvimCWk3BgD1iYkcMxzL2be2qyHQxDvQJGeQ=,tag:o1tuP0hkWsdeu1W7yrwmgw==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:SYFNmQQ+AFRPztZzf4Xt2eX1oNP0elaOTW0C,iv:2J0aPeh1zmlztbdhM9t9TdIC7IlhNxKATIW2LJ2LJZU=,tag:bCFwQb/52hmlhdVV4rBH6w==,type:str]
    OIDC_USE_PKCE: ENC[AES256_GCM,data:/NojWg==,iv:LXXFlwiSbS+NlIWlBdXrSs+sPeHxXsK/TaULf0c1Ed0=,tag:2rxHFhZHWFF89yt/Fg6TxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbnJ1V3ROUndONFFmbmpM
            ajY0OVBUcENHUFlPaUhXMHRDV1BPOWZKMG5JCjJTOEVqdG14akZPRzlzT0dzc0Jk
            TS9vU1ExaTAzMzNYdk1FSjJUT2hqVkkKLS0tIFYzVURlQUNoeXo3Q0ZtK0x5bEN2
            YUdycE5DVEVOa2JQWjJYamRZOFA3QVEKeoQW8yrrftaOf47nqbC8agR9uIWxIGkN
            nsseZn5dVK24yshnfgswO1KW2p4dDOfloM+n8f08FdXtEfo2IvG/KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-22T09:48:55Z"
    mac: ENC[AES256_GCM,data:QAHz8ESawZir9SRbqSX3rsoloThkmd+auffpK/vnuvqkWh7w2sKCgNrscdl8fvcxmCBpRvA1kK3ipGBHI6xeYhg3VMTOn5Bof00GavjiePpyqxglaQ9VpuvxYPoPeg1qOIF0UsSgk/9TwTDIKH1bpnc5BTjSKUO4lnrRwoRIFzg=,iv:OyS8YtTVQ3j8P+7mJZVh2fks8ORDg1ICQa/9xneG300=,tag:hn28Y+8njWzlW8d5GcLVLw==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
