clusterRoleBinding:
  create: false

config:
  pluginsDir: /build/plugins
  oidc:
    secret:
      create: false
    externalSecret:
      enabled: true
      name: headlamp-oidc-secret

initContainers:
  - name: headlamp-plugins
    image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
    imagePullPolicy: Always
    command:
      - /bin/sh
      - -c
      - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
    securityContext:
      runAsNonRoot: false
      privileged: false
      runAsUser: 0
      runAsGroup: 0
    volumeMounts:
      - name: headlamp-plugins
        mountPath: /build/plugins
  
serviceAccount:
  create: false

volumeMounts:
  - name: headlamp-plugins
    mountPath: /build/plugins
volumes:
  - name: headlamp-plugins
    emptyDir: {}
