clusterRoleBinding:
  create: false

config:
  inClusterContextName: "homelab"
  pluginsDir: /headlamp/plugins
  oidc:
    secret:
      create: false
    externalSecret:
      enabled: true
      name: headlamp-oidc-secret
    usePKCE: true
  watchPlugins: true

persistentVolumeClaim:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 100Mi

pluginsManager:
  enabled: true
  configContent: |
    plugins:
      - name: flux
        source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
        version: 0.6.0
      - name: cert-manager
        source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
        version: 0.1.1

serviceAccount:
  create: false

settings:
  configuration:
    plugins:
      "@kinvolk/kubernetes-prometheus":
        homelab:
          prometheusEndpoint: "infra-monitoring/vmsingle-vm:8428"
          prometheusSubpath: ""
