clusterRoleBinding:
  create: false

config:
  args:
    - "-cluster-name=homelab"
  pluginsDir: /build/plugins
  oidc:
    secret:
      create: false
    externalSecret:
      enabled: true
      name: headlamp-oidc-secret

initContainers:
  - name: headlamp-plugins
    image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
    imagePullPolicy: Always
    command:
      - /bin/sh
      - -c
      - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
    securityContext:
      runAsNonRoot: false
      privileged: false
      runAsUser: 0
      runAsGroup: 0
    volumeMounts:
      - name: headlamp-plugins
        mountPath: /build/plugins

pluginsManager:
  enabled: true
  configContent:
    - name: sample-plugin
      source: https://example.com/plugin.tar.gz
      version: 1.0.0

serviceAccount:
  create: false

settings:
  configuration:
    plugins:
      "@kinvolk/kubernetes-prometheus":
        homelab:
          prometheusEndpoint: "infra-monitoring/vmsingle-vm:8428"
          prometheusSubpath: ""

volumeMounts:
  - name: headlamp-plugins
    mountPath: /build/plugins
volumes:
  - name: headlamp-plugins
    emptyDir: {}
