# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-auth
type: Opaque
stringData:
    passwd: ENC[AES256_GCM,data:jNMMM8cj741CRbXvDLp7gfUc12H8tUJXaTTK6Z6q/f2pI4XMjFFkNpDT2kQXeHR07/7HM66X5FyNKAEXD/lTjhqWw9GX09eKMuPJWYuQbsPH3XaH/Ffgj4B44YNHC7dZC0OKvz4vnb5BWu1fyMnkTh3GEcNAAMsyRmrweaqJvjqqRBTzRL2hTWXHjd1ejHeUhQchW6yCB7pKV5sfOkUvJ6kEadbe6n44oqHoOzkZjD4JXa40hIuEyjo/rugV5l3U9Dw+aLwJX9aMHK+pZ232YfySN1U4FWYGAzT0/+ZfHAV3gruXXgkqKGfiUn+u5/u6cPWDVqK4p8UDKvs/jBMSLlcp6JPZHbxUzKc/k/tb9ilMZ4bh9Kord82KdU/bNkQgWOUZ/6Xb78kDo3b4UvbitIyQ1V6+jIJk63HqlygC6W2VlgMcfX+qusDw5AvtJTLqd9L/E4QxLmcEWYFYIW2l0yluxG89Jx1rjrYZLD8Ai1H3dwtOQk+MGEqzwFGB8aBtiIZ4N3wIz8MIzTGU/wJi+SUu4p079F5WEKMnaJxz3C21IyfIWsF+kLHwpy6BvYkvEJ26Xgj3gStyRkCWx2F0UdxFWCfUM8eRYZJqGV08S3MdQ+q9U7pf6ujBIKcI/ZX1JeU7Oka64UFITNRYamHz1r511ipc77sgJgRuAEh0oRYcfhi76OnR2pxSgR1HwdvazF/wxBppDKRVyshh9HUfRCtdVeiiUiVF5xMLY1eUKuC7HU0SqjdJ18jCJle8DkH9qa+P96E6niLTS5Y1LRrZoZRZFTZfpGvFx+/16EwEvyyEpl300aE=,iv:NAgGMsysaN/BrPvQ44tSuAglT3Y6m722h7/xv59R5tU=,tag:U388/PoX1+ywZYaPLMomGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T13:12:25Z"
    mac: ENC[AES256_GCM,data:PjxDtyOz56ZmZul4+zH8ttscc4z0CC7C4DDjw17Ba/gVVlt3ScKahm6sn3lFAtVx6ynKv2UkcK1xW5Hq7SXdzBVxlNcnEeSAm94rW0ndgzenBmUt2KJaqsh8npi7epfj9EsoTY2HBsYhRKWjkvVapwN6dtEQJqgCth+OjK4lwa0=,iv:cIP44gr2JEe3iY3G3Ns4gMeuGqx9SWaj7uESxp5Ylio=,tag:v1tkiqf5prBBFMHuqub2gw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
