controllers:
  mosquitto:
    pod:
      annotations:
        reloader.stakater.com/auto: "true"
    type: statefulset
    containers:
      mosquitto:
        image:
          repository: public.ecr.aws/docker/library/eclipse-mosquitto
          tag: 2.0.22
        env:
          TZ: ${CLUSTER_TIMEZONE}
        probes:
          liveness: &probes
            enabled: true
            port: &port 1883
          readiness: *probes
          startup:
            enabled: true
            spec:
              initialDelaySeconds: 30
              periodSeconds: 10
              failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 100Mi
    statefulset:
      volumeClaimTemplates:
        - name: config
          storageClass: longhorn-v2
          accessMode: ReadWriteOnce
          size: 1Gi
          globalMounts:
            - path: /config

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1009
    runAsGroup: 1009
    fsGroup: 1009
    fsGroupChangePolicy: OnRootMismatch

persistence:
  config-file:
    type: configMap
    name: mosquitto-conf
    globalMounts:
      - path: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
        readOnly: true

service:
  mosquitto:
    controller: mosquitto
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
      mqtt:
        port: *port
