prometheus:
  url:  http://vmsingle-vm.infra-monitoring.svc.cluster.local
  port: 8428

rules:
  default: false
  external:
    - seriesQuery: '{__name__="probe_success"}'
      resources:
        namespaced: false
      name:
        as: probe_success
      metricsQuery: max_over_time(<<.Series>>{<<.LabelMatchers>>}[1m])
