# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# Create key: ssh-keygen -t ed25519 -C "cluster-cronjob-badge-bot" -f ./id_ed25519 -N ""
# Configure in Github: Add the public key (id_ed25519.pub) to your GitHub repository under Settings ➔ Deploy keys and check „Allow write access“.
apiVersion: v1
kind: Secret
metadata:
    name: github-badge-bot-ssh
type: Opaque
stringData:
    #ENC[AES256_GCM,data:5Trb/4m2OrWeLSOAbY2faF80FkzPID1Dw+uJh/zHQYd9x7ozcG+ZHWJ5uYIzhx6LsDW10Q==,iv:kEcEKm8bNUOY6GA0vDMfQHjfGvWhvQ/z9FQFkMaFTgY=,tag:cHmIYqfzZh/D4U8Z4o9nQQ==,type:comment]
    identity: ENC[AES256_GCM,data:kNWH9JTLRekHQz9JCSlzSlXfHWyBCaocdNeMxWpgXmTEAhe83Tc/Zs0M478Qt04iHi7c7aMuI3gWVMbOAntN9EhK7JHpfLV2cn/oGgairAzpRdUaIDBbcI9ncicFCCisH7mXhFhz+hR83kUgPib8TZo40ECUgL0Pbe1aNS0K4TK7cYOAlu4x5PSAcvkPsEVCATSNFcCFHVrM5oBNFN2wWn6Stl/wwbkZRU9RNMyebrT55eUkk63OZxvotCJFaTNY5U616o5yFgpXlrTcAubv3EQejzU+4NQkMxX80j09xD1VEv0mwS+sguC6NsHsS5iuTVInYKvSEHpWpUgzi4wcBbhlTBKDGdh5jhfvlZtqeMYKFGw1M9zzJOxmDgbiVkDVAEHiK+stJ+WkA4gSIxf7g8TDJxCaj7fGKWCvDVcXfNZhwE4QVHvlIKAegMB1T8FyckaKsI492ajElNLbFhy9BBHgFpY+K60PvHT/WUuB1LlfItzoFAMoEH5bqCCpmRLSb2FL5BCJMHUT3aNybG+mp2BtW8QnQsLKjRw7,iv:9hdp1K8npqQ4DNEIEmjzAt4XEQYlK49Nc/OtVm+HcF4=,tag:hemPftepMW3zPMFQL9WbBw==,type:str]
    #ENC[AES256_GCM,data:DXrf4QnymSwh0dgdp5nTi+q3+/cQjcSEnodmo3NSv6xH9GB3T4JHd4w0rx5I2E9ee9nxH/IlbWPcQKKfVnVJwOFTfvQ=,iv:kH8dDwvokOj5Y6XezQcAn5OpnNLh+yIIbHPkTM+bzAs=,tag:ahiSaB24yZr5KCFQG7B5rA==,type:comment]
    known_hosts: ENC[AES256_GCM,data:DKDWK3cCo3i0nedaV3nFxivO+CRwZhDEL/dtfUfpuxJZxNdacyU1mF9gyZJ/4VUDAl45OJie2PXqrrNRZbKWHWDaxZC7YSynfQyMrqoZmoamRDzRteItsjuvTA==,iv:ovOUd0TtNr6y4oO4pDMBpNN/K4hQTbOeLo1imVia+60=,tag:7nnUHHZX/Pc7FxoWLhiOjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeXg0Qk9MUjJkRVh5MXE1
            RTNjS2M2aW1URE04TjN6Z0R6ZDIwaE9NcFhJClZuRURYVFVxV2ZFTXczeFNadFRN
            dEFQZFZ4ei9GZVdvWHY3S2JJR3JPWlUKLS0tIHQvd0dZYmdSeUc1b00xRlZ5Nisx
            V0Y3WkN0aDE1QWh0U3p6T2g3cHh6N2MKIigsVI2OKs6SwEJfiCZTk5NQXBdLJh4L
            BhLaJdwcTbCcBAj6iOC1NFGvNWGTGCKD5ff06mafxMxqktTEJoZjDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T20:46:55Z"
    mac: ENC[AES256_GCM,data:FFpbt0ha64C2c5elNkJTvg+tPqrEptQr8Esehim/mhSJf4wFQeYDMNXWl+u45w+d7jld67Nl8m0uAZK4geO1nZr7V3gNiqvvMmWqyGcZJ/EqLpRn8zGaGIPVtfrtA9/0OcFe7dNodssLEX4BeQOWvdOkGD6VS/TKUZOcWZILTww=,iv:FZbeqRfDyTRt/jPDKutXfGl2Wmi2p1os5HdFqkKnBhA=,tag:su+xnc7dCO+bndBSkeAxTQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
