# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# TO BE DONE
#
# Create key: ssh-keygen -t ed25519 -C "cluster-cronjob-badge-bot" -f ./id_ed25519 -N ""
# Configure in Github: Add the public key (id_ed25519.pub) to your GitHub repository under Settings ➔ Deploy keys and check „Allow write access“.
apiVersion: v1
kind: Secret
metadata:
  name: github-badge-bot-ssh
type: Opaque
stringData:
  # The exact contents of your private id_ed25519 file:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    ...
    -----END OPENSSH PRIVATE KEY-----
  # Known_hosts entry for github.com to bypass interactive SSH prompts:
  known_hosts: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
