# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# Create key: ssh-keygen -t ed25519 -C "cluster-cronjob-badge-bot" -f ./id_ed25519 -N ""
# Configure in Github: Add the public key (id_ed25519.pub) to your GitHub repository under Settings ➔ Deploy keys and check „Allow write access“.
apiVersion: v1
kind: Secret
metadata:
    name: github-badge-bot-ssh
type: Opaque
stringData:
    #ENC[AES256_GCM,data:5Trb/4m2OrWeLSOAbY2faF80FkzPID1Dw+uJh/zHQYd9x7ozcG+ZHWJ5uYIzhx6LsDW10Q==,iv:kEcEKm8bNUOY6GA0vDMfQHjfGvWhvQ/z9FQFkMaFTgY=,tag:cHmIYqfzZh/D4U8Z4o9nQQ==,type:comment]
    identity: ENC[AES256_GCM,data:Dp9MFmM5f5tc/GFiMvvkdd6pfBt7XDUrIwrvR7oEMGeudOvTvM+F68tdx5GmEqtkbVEbfGr6+vHDb5g52VPEbsLEMMEbZCW9ZKVDsznV3IbC0SMB3lz/Danm1wKcrcQIL1VNwz7RA7xzhiDeZwp2Qlc8wbsUoigYux5K80r9SCnmqnX1mIbs+Gv/U/NQYs8GiIfsraHHi9JgeFKYretfxomt2+FNeUq54qf59eBLnAydBSouq1rLPjCIbQBQuVG08HxXtMIiy0zUV2Po3YqKc6irMd04ONhq0RUFGtjLGZvUv3GGQbL+xZ5t3yumUjT9x9nWApRkitQoRkK9P3FsfHozi+s9Yjvu88oWlvYowtxWHBi4IHWA2elab7pgAafI4j7V2iB4DwbzJAqo6s/FSdm/HDArUpRgl+Dn1+ZpbasGvaBC50nQdWhqsRDbro+RbDQDrC3HcvxbTD0ar34jSf7cUHratuqNcaERym3BZLjRl6q5x99cRd8jP3ohwO3ULGaoF5v3IK406IkHf0tVXVH5kRIj9XwFdf11,iv:UhTwHZy4+C6eKRUPZ5Iy9c1OwT973LapsNcI9TIv6eQ=,tag:bwDQIQAcGaCgp+uMHirnEQ==,type:str]
    #ENC[AES256_GCM,data:DXrf4QnymSwh0dgdp5nTi+q3+/cQjcSEnodmo3NSv6xH9GB3T4JHd4w0rx5I2E9ee9nxH/IlbWPcQKKfVnVJwOFTfvQ=,iv:kH8dDwvokOj5Y6XezQcAn5OpnNLh+yIIbHPkTM+bzAs=,tag:ahiSaB24yZr5KCFQG7B5rA==,type:comment]
    known_hosts: ENC[AES256_GCM,data:DKDWK3cCo3i0nedaV3nFxivO+CRwZhDEL/dtfUfpuxJZxNdacyU1mF9gyZJ/4VUDAl45OJie2PXqrrNRZbKWHWDaxZC7YSynfQyMrqoZmoamRDzRteItsjuvTA==,iv:ovOUd0TtNr6y4oO4pDMBpNN/K4hQTbOeLo1imVia+60=,tag:7nnUHHZX/Pc7FxoWLhiOjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeXg0Qk9MUjJkRVh5MXE1
            RTNjS2M2aW1URE04TjN6Z0R6ZDIwaE9NcFhJClZuRURYVFVxV2ZFTXczeFNadFRN
            dEFQZFZ4ei9GZVdvWHY3S2JJR3JPWlUKLS0tIHQvd0dZYmdSeUc1b00xRlZ5Nisx
            V0Y3WkN0aDE1QWh0U3p6T2g3cHh6N2MKIigsVI2OKs6SwEJfiCZTk5NQXBdLJh4L
            BhLaJdwcTbCcBAj6iOC1NFGvNWGTGCKD5ff06mafxMxqktTEJoZjDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T20:09:22Z"
    mac: ENC[AES256_GCM,data:HdfQQG6q2t7IHbNsK0Eb4nZBiM+TT/lo8GebwTpT9kso1IHDUep/9XClsTfmfKGQJS/D8xNMjxmZeEowhyX7yuK92Gw6qp+mvg3Ia2HCW2aJIbzX864SfqnpfW1WISSDplb5y/VU2TEHkaxnCMyyO3UE9ShSpWjazkW6L+KoeQM=,iv:USJauURwAKodulGxAzou7xfVc4HfnTisTsmjHy4slkU=,tag:/R/5UJcvrBI37N1QKgk7Gw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
