# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: private
  namespace: infra-tailscale
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "private.${CLUSTER_DOMAIN}, *.private.${CLUSTER_DOMAIN}" # ExternalDNS configuration to push records automatically to Cloudflare
    tailscale.com/expose: "true" # Expose this gateway to your Tailnet
    tailscale.com/hostname: "homelab-private-gateway"  # Device name in Tailscale Admin Console
spec:
  # Natively managed by your existing Cilium CNI (replaces Envoy)
  gatewayClassName: cilium
  listeners:
    # Listener 1: Handles all application subdomains (*.private.myhomelab.com)
    - name: https-wildcard
      protocol: HTTPS
      port: 443
      hostname: "*.private.${CLUSTER_DOMAIN}"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret 
            name: private-wildcard-tls
            namespace: infra-cert-manager
    # # Listener 2: Handles the root private domain
    # - name: https-root
    #   protocol: HTTPS
    #   port: 443
    #   hostname: "private.${CLUSTER_DOMAIN}"
    #   allowedRoutes:
    #     namespaces:
    #       from: All
    #   tls:
    #     mode: Terminate
    #     certificateRefs:
    #       - kind: Secret
    #         name: private-wildcard-tls
    #         namespace: infra-cert-manager
