# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connector.yaml
  - gateway.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - namespace.yaml
  - secrets.enc.age.yaml

configMapGenerator:
  - name: tailscale-operator-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
