apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: cilium-bypass
spec:
  statefulSet:
    pod:
      annotations:
        ingress.cilium.io/bypass-socket-lb: "true"
      tailscaleContainer:
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
