# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
type: Opaque
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:TO_BE_GENERATED,...]
