# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
stringData:
  client_id: ENC[AES256_GCM,data:Q5sv1YDZYASyrjtJ5DurY1OmVFfocIADCu+VwA==,iv:0lkE0hqzVqBAWCwHOpuSgBpguHCq4JNj+1hEt1EZl80=,tag:NFRyRoEAwPC7JGd6EXgLEQ==,type:str]
  client_secret: ENC[AES256_GCM,data:krlhRVU8nECxtUVXcSEr5zWNtCXj/SeWYNj8AqQZZBM=,iv:CbebUzZdbzF10ZeoU/rxxqziuScULvMMhZHVcckFlVU=,tag:6zGZdvjpWylq2iveFpl38Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeXg0Qk9MUjJkRVh5MXE1
        RTNjS2M2aW1URE04TjN6Z0R6ZDIwaE9NcFhJClZuRURYVFVxV2ZFTXczeFNadFRN
        dEFQZFZ4ei9GZVdvWHY3S2JJR3JPWlUKLS0tIHQvd0dZYmdSeUc1b00xRlZ5Nisx
        V0Y3WkN0aDE1QWh0U3p6T2g3cHh6N2MKIigsVI2OKs6SwEJfiCZTk5NQXBdLJh4L
        BhLaJdwcTbCcBAj6iOC1NFGvNWGTGCKD5ff06mafxMxqktTEJoZjDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T21:13:48Z"
  mac: ENC[AES256_GCM,data:QPavw1zSlck+Vjbl+jXBF8hoXW42kKbQPpyGfyFr6iBQmX75LlBraeV7EqFtjifqKC/mGKQhdZ+1dxG4cTWw68Xkz4+N+KZ+rpIT0cY9vttdYayO9fi8Zuxk4J6zABzi+00EYZp6OgtEbCxEhjdZImKTlzGYD/p8MjQqbNQrW40=,iv:F6jBb56HQviRMpI4EIhDObcsKGrw63oQjNp87hkt27c=,tag:sz4fGN7nrhTC/mY3FBQstA==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
