# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-wildcard
  namespace: infra-gateway
spec:
  secretName: public-tls

  dnsNames:
    - "*.${CLUSTER_DOMAIN}"

  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
