---
controllers:
  plex:
    pod:
      annotations:
        reloader.stakater.com/auto: "true"
      # Soft anti-affinity: prefer not to share node with other GPU apps
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: immich
                topologyKey: kubernetes.io/hostname
      resourceClaims:
        - name: intel-gpu
          resourceClaimTemplateName: plex-gpu
    containers:
      plex:
        image:
          repository: ghcr.io/home-operations/plex
          tag: 1.43.3.10896@sha256:4f1d88882a9883cc525e7c84b22c67c57416b7d3b35c3412329eeb07786433a7
        env:
          PLEX_ADVERTISE_URL: https://plex.${CLUSTER_DOMAIN}:443
          PLEX_ALLOWED_NETWORKS: "${HOMENET_CIDR},10.244.0.0/16,10.96.0.0/12" # Home Net, Cilium Pod, K8s Services
          PLEX_CLAIM:
            valueFrom:
              secretKeyRef:
                name: plex-secrets
                key: PLEX_CLAIM
          TZ: ${CLUSTER_TIMEZONE}
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /identity
                port: &port 32400
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 60
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 100m
            memory: 1500Mi
          limits:
            memory: 6Gi
          claims:
            - name: intel-gpu

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1005
    runAsGroup: 1005
    fsGroup: 1005
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups: [44, 10000]
    seccompProfile: { type: RuntimeDefault }
  nodeSelector:
    feature.node.kubernetes.io/pci-0300_8086.present: "true"  # 0300 = Graphics Class, 8086 = Intel Vendor ID

persistence:
  config:
    accessMode: ReadWriteOnce
    storageClass: "longhorn-v2"
    size: 10Gi
    globalMounts:
      - path: /config/Library/Application Support/Plex Media Server
  cache:
    accessMode: ReadWriteOnce
    storageClass: "longhorn-v2"
    size: 20Gi
    globalMounts:
      - path: /config/Library/Application Support/Plex Media Server/Cache
#  media:
#    type: nfs
#    server: ${STORAGE_IP}
#    path: /mnt/storage0/media
#    globalMounts:
#      - path: /media
#        readOnly: true
  logs:
    type: emptyDir
    globalMounts:
      - path: /config/Library/Application Support/Plex Media Server/Logs
  tmp:
    type: emptyDir
    advancedMounts:
      plex:
        plex:
          - path: /tmp
            subPath: tmp
          - path: /transcode
            subPath: transcode
route:
  plex:
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Entertainment
      gethomepage.dev/name: Plex
      gethomepage.dev/icon: plex.png
      gethomepage.dev/description: Media Player
      gethomepage.dev/widget.type: plex
      gethomepage.dev/widget.url: http://plex.entertainment:32400
      gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_PLEX_TOKEN}}` }}"
    hostnames:
      - plex.${CLUSTER_DOMAIN}
      - plex.internal.${CLUSTER_DOMAIN}
      - plex.private.${CLUSTER_DOMAIN}
    parentRefs:
      - name: internal
        namespace: infra-gateway
      - name: private
        namespace: infra-tailscale
      - name: public
        namespace: infra-gateway
    rules:
      - backendRefs:
          - name: plex
            port: *port

service:
  plex:
#    type: LoadBalancer
#    annotations:
#      lbipam.cilium.io/ips: 
#    externalTrafficPolicy: Local
    controller: plex
    ports:
      http:
        port: *port
        appProtocol: kubernetes.io/ws # Explicitly handles Plex's persistent WebSockets
