---
controllers:
  musicassistant:
    containers:
      musicassistant:
        image:
          repository: ghcr.io/music-assistant/server
          tag: 2.10.5@sha256:28023f8c0d96ca2496391f3218a6d70d7ef3ba84db846b3a3f3cd9ce7ef8aedc
        env:
          TZ: ${CLUSTER_TIMEZONE}
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &maPort 8095
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            spec:
              initialDelaySeconds: 30
              periodSeconds: 10
              failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 2Gi
  sonos-ssdp-relay:
    pod:
      # Required to listen to UPnP/SSDP traffic
      hostNetwork: true
      # Ensures the pod can still resolve internal cluster services while using hostNetwork
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        seccompProfile: { type: Unconfined }
    containers:
      relay:
        image:
          repository: firbykirby/udp-broadcast-relay
          tag: v1.3.0-rc1@sha256:b4d9f842739878373c34d43c3ba2472c814fc3f674576735d1521d0a615a425a
        env:
          ID: "1"
          PORT: "1900"
          DEV: "enp1s0 cilium_host" # Host's physical interface and Cilium gateway interface
          MULTICAST: "239.255.255.250" # Sonos SSDP multicast group
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1011
    runAsGroup: 1011
    fsGroup: 1011
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups: [44, 10000]
    seccompProfile: { type: RuntimeDefault }

persistence:
  data:
    accessMode: ReadWriteOnce
    labels:
      volsync.backube/restore: "true"
    storageClass: longhorn-v2
    size: 1Gi
    globalMounts:
      - path: /data

route:
  musicassistant:
    hostnames:
      - musicassistant.internal.${CLUSTER_DOMAIN}
      - musicassistant.private.${CLUSTER_DOMAIN}
    parentRefs:
      - name: internal
        namespace: infra-gateway
      - name: private
        namespace: infra-tailscale
    rules:
      - backendRefs:
          - name: musicassistant-ui
            port: *maPort

service:
  ui:
    controller: musicassistant
    ports:
      http:
        primary: true
        appProtocol: kubernetes.io/ws
        port: *maPort
  streaming:
    controller: musicassistant
    type: LoadBalancer
    externalTrafficPolicy: Local # Crucial to preserve client source IPs for Sonos
    annotations:
      io.cilium/lb-ipam-ips: ${CLUSTER_LB_MUSICASSISTANT} # Music Assistant dedicated IP necessary for local player discovery (mDNS/uPnP/...)
    ports:
      streaming:
        port: 8097
