---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-lan-router
  namespace: infra-tailscale
spec:
  replicas: 1
  hostnamePrefix: homelab-lan-router
  subnetRouter:
    advertiseRoutes:
      - "${HOMENET_CIDR}"
