---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - cert-manager/ks.yaml
  - cilium/ks.yaml
  - external-secrets/ks.yaml
  - flux/ks.yaml
  - gateway-api/ks.yaml
  - grafana/ks.yaml
  - prometheus/ks.yaml
#  - tailscale/ks.yaml
