---
args:
  # Skip TLS verification for kubelet certificates - necessary because Talos uses self-signed kubelet certs
  - --kubelet-insecure-tls

podDisruptionBudget:
  enabled: true
  minAvailable: 1

replicas: 2

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 500m
    memory: 500Mi

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
