# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
metadata:
    name: smtprelay-creds
stringData:
    SMTP_RELAY_HOSTNAME: <tbd>
    SMTP_RELAY_SERVER: <tbd>
    SMTP_RELAY_USERNAME: <tbd>
    SMTP_RELAY_PASSWORD: <tbd>
kind: Secret
