# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:vAQ9ln8=,iv:UarMHQekaSeMMsmc7107b/NB8Aw1pNCwdHOsKirfYq0=,tag:dCYUWEZjjmIxtgR2X5VJmA==,type:str]
    #ENC[AES256_GCM,data:TeBGXXrI/5UfnDt7LfLkq0SVMTWSY2hNXrc6DEDEAoYKVhWlDrrfji5z46QzDPPPmmthGw5ObwaXhzTsJEvZSujZeWAG8vzoqQSL7/A1Z6Qfi8Lyld94now1OoFjR+ga,iv:zVhcfUmDtdpOK+lU6CWot1c0wELOKnI0SCwgkkECAZI=,tag:gopz/jmuxKaQM1gZRYFBcg==,type:comment]
    password: ENC[AES256_GCM,data:PPQY2NFH/Cs3YtTOt+OKUIy5fjNQWC6alQKWJaevFwtIhYOjrQe9f79z81XWFy2AY0fcwEYLr/SH5o1t,iv:8OrjaS4HnEw1pox0YSQfMPXpK+VsDcQnvz7r2wv7kpA=,tag:cpoHV4YuxUTXN1xSFpy+Ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL0M2RFFOaG9mUnZwNUFa
            cWg1Wlc3THFKUTZNcTFvd2ZZZkdrN1RtVndFCno4V0JZMjZVTFdFbHQwT1FBQkR3
            VlRRNmVZd0c4TlVkRGVxSENVN0Q5WVkKLS0tIDF1UkIwai9wQ3laOW1uRFhTb0M0
            bVdMUzRjUS9qRTBUOUFOSkFydFgzekUK/YMQ5ve4uwL/DHJd0LX7/3BRfB3lOZzz
            PXki4KjfupY3w9wly923bMdVOoQeaOI997Y3F8dc7S4YHLNF9AYr3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T21:30:05Z"
    mac: ENC[AES256_GCM,data:u4GHBD10Uy8gTgZKQJ01uBXpNpIJrOzxI/dyLM4hudQ62KbzzCvyR0BWsd4T34NeThLUlH6Nls620wL31VFhddf5hcts7IHRZaE/nio4Tu8XU6a5OLiyCRVzzepN8nax/lf+Dn4dAL7Fa211BHk68L9SUdK6ca/L3UZgkuxfsUg=,iv:Jx0fYGxF5GrG4SZZNA19vmtZpxmUMJlAmX23cUXNfeg=,tag:t0UQn4lznHPlYX8yW2aNZA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
