# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: esphome-secret
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:zWEvE4BEPIckgwM4/IhBb+eE++I/mB0XPc1MZgz67Mwl9KU7hGOcC3Eiw0yMdQOcfD/aMG1mnsPHQ2QT,iv:9bfg74EpzQpE5Wu6WyFXNI1jIxCBAq6Jc1cJp4PY5O4=,tag:V2mtJb5hx33BKHlEEzKTCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T19:07:01Z"
    mac: ENC[AES256_GCM,data:MFPUBxMe1decSk39b+ptr31ppKuObtYti1FEim8gzMZRCw2Q6OGkR1jAa9qjBVA+oKtskpmYORbKqliHx8dNzDfYbvvNQQ0hoW1WZmOeuw1+rdSHo1Nf7ilZszSxFPQo/hX4NeihxI8Fp15EKdOwSf33jHvjQrE5a3b3eAHvvtw=,iv:Xy24rUC0685wj1m2BXP57CdUKFqksMhOjI/rGFr9RGw=,tag:e5C4SX8f0uoDpfE6oqx9cw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
