---
controllers:
  esphome:
    containers:
      esphome:
        image:
          repository: esphome/esphome
          tag: 2026.9@sha256:4ad55931c0186d2910dc128526237acabb422a662697a4e8bb356d390a1332a1
        env:
          TZ: ${CLUSTER_TIMEZONE}
          # ESPHOME_DASHBOARD_USE_PING: "true"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &port 6052
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            spec:
              initialDelaySeconds: 30
              periodSeconds: 10
              failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
          limits:
            memory: 1Gi

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1011
    runAsGroup: 1011
    fsGroup: 1011
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups: [44, 10000]
    seccompProfile: { type: RuntimeDefault }

persistence:
  config:
    accessMode: ReadWriteOnce
    labels:
      volsync.backube/restore: "true"
    storageClass: longhorn-v2
    size: 1Gi
    advancedMounts:
      esphome:
        esphome:
          - path: /config
  tmp:
    type: emptyDir
    advancedMounts:
      esphome:
        esphome:
          - path: /tmp
  pip-cache:
    type: emptyDir
    advancedMounts:
      esphome:
        esphome:
          - path: /home/esphome
  secrets-file:
    type: secret
    name: esphome-secrets
    advancedMounts:
      esphome:
        esphome:
          - path: /config/secrets.yaml
            subPath: secrets.yaml

route:
  esphome:
    hostnames:
      - esphome.internal.${CLUSTER_DOMAIN}
      - esphome.private.${CLUSTER_DOMAIN}
    parentRefs:
      - name: internal
        namespace: infra-gateway
      - name: private
        namespace: infra-tailscale
    rules:
      - backendRefs:
          - name: esphome
            port: *port

service:
  ui:
    controller: esphome
    ports:
      http:
        primary: true
        appProtocol: kubernetes.io/ws
        port: *port
