# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: influxdb3-secrets
type: Opaque
stringData:
    INFLUXDB3_AUTH_TOKEN: ENC[AES256_GCM,data:STDVA2mc93Bg9BGQCi8/j5/8ji+Jo94CUcd6JxW0SKHycSPNm+BmOQBxNZ3zI98TvJcnXORLMaBG8Djdn4mT4qviohVLwf3EwdGuyGafffYdbXYVY1qgC7uefJY=,iv:b8lMbIVGTpT1+SFNTMrYm87cA4TCgVwtzTNMGzBTGi8=,tag:WDeGgM3jWP/HtKhjFOTTiA==,type:str]
    INFLUXDB3_LICENSE_EMAIL: ENC[AES256_GCM,data:8LcQ+dEbGIuRzScY+Q==,iv:EsqF2DmY6tDRZDxwkXHA4HJJjRbHqdO4xec9JiSufpA=,tag:NHpzrCLcBFRVhru4jSS8Kg==,type:str]
    INFLUXDB3_LICENSE_TYPE: ENC[AES256_GCM,data:Ams8OA==,iv:Njslc3UqDuFMeEpN4TtqCqtyBcPddFJH5uHKyJfpUk0=,tag:7T8gb6fzvfmthJVCakbXtQ==,type:str]
    INFLUXDB3_WEBUI_SESSION_SECRET: ENC[AES256_GCM,data:fsEU7jGDMnvS2B4GhAwBSsPREKRbA2ktLoBaYDNmp9/USNtfwnCvIQzhDakN91IR01IzlcMnsPnWohHXWTbh5ZRP1odFokow4ij/uSrAKsyBKrW0kGDYDA==,iv:vbiOJGAcv9ygd6sRjKazFHY/MNEwCSRLCgR9n27rRjE=,tag:snkEnAu5ONRGiiXiLza13Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T20:39:01Z"
    mac: ENC[AES256_GCM,data:TCx757MJwLzVJv/PUuU39Nw7x3Lnde3kEHviZ3WOkfrAg2XCPuy3QkniATVw4eCR6aX5TS+vzos7yDWzPbPxhN5VYOQPmDxPPsqvMzdUjR40MgnOSfakXWPqOwwaw/WKqvIpGflTDPw00jwTfIMf4iU93kSsj6FBupQakHqS910=,iv:QvrGe0E1NNGx9hBdkVTO11omecJjSyvnsKWahtoR3eU=,tag:oo2+AEHrRghqu+IUVqFeLg==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
