# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: influxdb3-secrets
type: Opaque
stringData:
    INFLUXDB3_AUTH_TOKEN: ENC[AES256_GCM,data:m1EuIs5BPCsXGyuJshLLvqAY0VkSqxY5DLq++uJh3BvwkSTeJbMP5PlBhzU=,iv:xhv3x9R0D4iaNk99DVN++DKV8bafGClkPaI2WuUejQc=,tag:7dvM5K0J0pYQSQzm2hP7bg==,type:str]
    INFLUXDB_TOKEN: ENC[AES256_GCM,data:DeaS8BelEmM30yxD/yt66b2j+AF5OIUv66oIoy+E7BhOJYecx8ZQXXFcH/0=,iv:ye3a7yU+RbRLoiPqU2kPWCK6rRd1rGLkJw0Lut/Ctt0=,tag:xgu6LoQhH6Hw8pLeZNj8vg==,type:str]
    SESSION_SECRET_KEY: ENC[AES256_GCM,data:l4xltLxM1otnugIa9U8Wmzo7itVZOYjaaGdP6KyvzaWmA3pPIb9K7x/7uY7tbRVEIBtZDdv+uPPBAe8tqWET1EFgc3VmxiJTjFWwDvErrEo0yLTSOQC8hg==,iv:DFt63497hMpcYWFHMEv46ZuYw1DHOWLDXuG+XbuJ33E=,tag:APhY9H9XnGDkoxBhVVPS9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T20:38:43Z"
    mac: ENC[AES256_GCM,data:gqrVemahtSu3I4gwTAL2lVVlWbdRtjDzBZ4ZKAFTVWwYYy8r1NbeAGJXmj9YmO5ylXNGYVnz6RnfAaMrcygMTFje/Cly5gTkGz+w3pklhYHLWfsiGlvrZnIsmJE0Ut3TVQTR1GUHsFOFaaXH7Fim4D4Iu+5zBgU2MiPOxkDbWyg=,iv:I+lsJWU9/KRfCQLnWTsoitvk0LKRg+06l+6vph56CVs=,tag:hySr6eLBLeCpKLrz225lnw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
