# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: influxdb3-secrets
type: Opaque
stringData:
    INFLUXDB3_AUTH_TOKEN: ENC[AES256_GCM,data:m1EuIs5BPCsXGyuJshLLvqAY0VkSqxY5DLq++uJh3BvwkSTeJbMP5PlBhzU=,iv:xhv3x9R0D4iaNk99DVN++DKV8bafGClkPaI2WuUejQc=,tag:7dvM5K0J0pYQSQzm2hP7bg==,type:str]
    INFLUXDB_TOKEN: ENC[AES256_GCM,data:DeaS8BelEmM30yxD/yt66b2j+AF5OIUv66oIoy+E7BhOJYecx8ZQXXFcH/0=,iv:ye3a7yU+RbRLoiPqU2kPWCK6rRd1rGLkJw0Lut/Ctt0=,tag:xgu6LoQhH6Hw8pLeZNj8vg==,type:str]
    INFLUXDB3_LICENSE_EMAIL: ENC[AES256_GCM,data:8LcQ+dEbGIuRzScY+Q==,iv:EsqF2DmY6tDRZDxwkXHA4HJJjRbHqdO4xec9JiSufpA=,tag:NHpzrCLcBFRVhru4jSS8Kg==,type:str]
    INFLUXDB3_LICENSE_TYPE: ENC[AES256_GCM,data:Ams8OA==,iv:Njslc3UqDuFMeEpN4TtqCqtyBcPddFJH5uHKyJfpUk0=,tag:7T8gb6fzvfmthJVCakbXtQ==,type:str]
    SESSION_SECRET_KEY: ENC[AES256_GCM,data:l4xltLxM1otnugIa9U8Wmzo7itVZOYjaaGdP6KyvzaWmA3pPIb9K7x/7uY7tbRVEIBtZDdv+uPPBAe8tqWET1EFgc3VmxiJTjFWwDvErrEo0yLTSOQC8hg==,iv:DFt63497hMpcYWFHMEv46ZuYw1DHOWLDXuG+XbuJ33E=,tag:APhY9H9XnGDkoxBhVVPS9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T13:34:43Z"
    mac: ENC[AES256_GCM,data:qCb9uInw7NeDf8skWNKqNsempQ7ETlyIwLROzlSo2ZYUTQrBjXEVW4OO8FI4GaR8y7KtfgzcnTTUhO1VUYf1oXuHj2AQ8a9LaP+koi/FD/D6TvVkvlOKLMiOMh5QgfagAsJmIL4FEPv887tjn0tNiALZsbc/KVs3+oPmCQMvwDI=,iv:chjZwS05gGhoTrNuTZ5LJBP9y2vXGhpNEDVaxEAoXus=,tag:SjUbP9cLV/t3R3LuiFXMFw==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
