controllers:
  influxdb3:
    containers:
      main:
        image:
          repository: influxdb
          tag: 3.12.0-enterprise
        env:
          INFLUXDB3_CLUSTER_ID: "cluster0"
          INFLUXDB3_NODE_ID: "node0"
          INFLUXDB3_OBJECT_STORE: "file"
          INFLUXDB3_DATA_DIR: "/var/lib/influxdb3/data"
          INFLUXDB3_PLUGIN_DIR: "/var/lib/influxdb3/plugins"
          INFLUXDB3_MODE: "all,webui"
          INFLUXDB3_DISABLE_AUTHZ: "health,ping,metrics"
        envFrom:
          - secretRef:
              name: influxdb3-secrets
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /health
                port: &port 8181
              initialDelaySeconds: 15
              periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi

service:
  influxdb3:
    controller: influxdb3
    ports:
      http:
        port: *port

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1500
    runAsGroup: 1500
    fsGroup: 1500
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile: { type: RuntimeDefault }

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn-v2
    accessMode: ReadWriteOnce
    size: 15Gi
    advancedMounts:
      influxdb3:
        main:
          - path: /var/lib/influxdb3/data
            subPath: data
          - path: /var/lib/influxdb3/plugins
            subPath: plugins
  ui-tmp:
    enabled: true
    type: emptyDir
    advancedMounts:
      influxdb3:
        main:
          - path: /tmp
            subPath: tmp
route:
  influxdb3:
    hostnames:
      - influx.internal.${CLUSTER_DOMAIN}
      - influx.private.${CLUSTER_DOMAIN}
    parentRefs:
      - name: internal
        namespace: infra-gateway
      - name: private
        namespace: infra-tailscale
    rules:
      - backendRefs:
          - name: influxdb3
            port: *port
