# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: sops-age
spec:
  namespaces:
    - infra-flux
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: gcp-secretstore
      kind: ClusterSecretStore
    target:
      name: sops-age
    data:
      - secretKey: age.agekey
        remoteRef:
          key: homelab-sops-global
