# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secretstore
spec:
  provider:
    gcpsm:
      projectID: ${GOOGLE_SM_PROJECT_ID}
      location: ${GOOGLE_SM_LOCATION}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gsm-auth
            key: credentials.json
            namespace: infra-flux
