# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
  namespace: infra-flux
spec:
  path: ./kubernetes/applications/apps/paperless/app
  targetNamespace: app-paperless-ngx
  interval: 15m
  retryInterval: 1m
  timeout: 3m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
  # components:
  #   - ../../components/volsync
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      APP: paperless
      APP_UID: "1000"
      APP_GID: "65542"
      VOLSYNC_CLAIM: paperless-data
      VOLSYNC_CAPACITY: 15Gi

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis
  namespace: infra-flux
spec:
  path: ./kubernetes/applications/apps/paperless/redis
  targetNamespace: app-paperless-ngx
  interval: 15m
  retryInterval: 1m
  timeout: 3m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
