# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless
  namespace: infra-flux
spec:
  path: ./kubernetes/applications/apps/paperless/app
  targetNamespace: app-paperless-ngx
  interval: 15m
  retryInterval: 1m
  timeout: 3m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
  dependsOn:
    - name: volsync
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: paperless-ngx
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_MINUTE: "15"
      VOLSYNC_S3_HOUR: "4"
      VOLSYNC_S3_MINUTE: "0"
      VOLSYNC_UID: "1001"
      VOLSYNC_GID: "1001"

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis
  namespace: infra-flux
spec:
  path: ./kubernetes/applications/apps/paperless/redis
  targetNamespace: app-paperless-ngx
  interval: 15m
  retryInterval: 1m
  timeout: 3m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
  decryption:
    provider: sops
    secretRef:
      name: sops-age
