---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
spec:
  interval: 30m
  chart:
    spec:
      chart: zitadel
      version: "10.0.2"
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: infra-auth
  dependsOn:
    - name: postgres
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: zitadel-values
      valuesKey: values-zitadel.yaml

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 18.7.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: infra-auth
  valuesFrom:
    - kind: ConfigMap
      name: postgres-values
      valuesKey: values-postgres.yaml
