# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:RTyCiYo5MjKjwFhCAxHzN7jegSJiuIRzOf3466+k+YfLtlgYmsoJw9zQXVn7hd/jDsqEa4CGqsPZmmA+Jlo7kUZV0/2C6JQPJWT0Za3HetxB7VHB/Z3PC1+k0jWGa0XoR6MEmNuqYqX+irUNlgvFhRzdfdU2x5yr9HHL0Poj2X5LwXFdGOVuCzwtaWLnMQ8lCz+7PbAKYsdmKeNSQO4UNFJyVTpfym4ABJjlqrZ7HeYhMm8zkb0erNwmOms1FyLCDGu9+6zxgpxgcYVF6zYrpeN3kIo7iDAEhbaLiASqrw3pFfSL2WHVqBvpjBm1Rjuz3oAdAUxMYO+FEwiV89f76xULTJjFXF0i//xSThNWgYBsQ4vrYDBslvLXdhtLXGFZXMLn6UwvXMLcNKkJpGDhbz8VUwdJ3x9jZu7ciRfiSL+jTK1lp+Gt5i6hmVFFatsT5M+r6G4uv1aJOVfGKSNC8IxZfnxUrQkoLSvqCOn+w7dYHeDyZZ2S2pKuJVuxbypy7dpOSSNFnto9IemX2T+zX7mIiCqICFbGc5vyeDfk7cYoq9nGPd+QLiVefNdFUP7bI3hX5mP9hIz8BOt4JhI+U7wmgCqyO0mGyOeIONAouUg5c2BvaGvLqBiYmPAG/iP0uR0w8kBDhNfhSRGb6AkF334cKMJZqaUJhDHuxT4KbJUwYR35D7AHFj3fuyTsIM4KqaMiBKRlmFvKCvLfbYB/+oUeneYEpBapqUj6RiLweHMuUtKSZfoK4fgdCDVCyv8KF/O9sSlsRHtc5EThrULC15ICtEk4U5Ga8uT/ljJjZZNkyGevNUqYLs0VfZwp6xpmRrksEHCdPSxhgTmF752BcaLzWLSQvdziPE9pKADPLbEN7grsbKSm0HGJ33nDOskQOEejaUlgChyMkFAHxvVb9jYCuOp0Ktk0xiecT8O+zpSMAuSvr2nCchWgqclV7y9PVl9SLmEB+AZ0s0Dqxmmde6LacA3oLkvTaZGJqyf9FsxLRLZsT1PazBde9hsPJ5J0jaIL+7ZwVHCTcWZCM8zhnXffdDBAkE9NA47ameX7jOxyjgEaWSSihUDszjScK3lFWpepMGC4JeWYajtWU/dRlE/7UO/qOTOjL+Jg6iRKKaZo4AY=,iv:0aTbMRJgjnIznedHfxRPyPU5yjc1cVGoO/vOeBSbJsQ=,tag:LdUKHhjYeUAjQfJ4AOuztg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T22:22:16Z"
    mac: ENC[AES256_GCM,data:hyZ4D/e8o7VU7/ODLkgIEKF7kP5CFgX9TfDlOghJ5cagiMAtzOg1yl/sEruQHOwh63JbVsTkxr0VbSFJ6GIcBHLWpgdHLiYH05N+PA+Alpk6KmIENDe+wKIfAnA0oON9mvX9In+Btt0mXc62KKjB6RTaCZ9k1UIiqu+HMlQkPVc=,iv:9JkUgIFMrAW3SYTEBeh6Uvj6F/pviQYKRlVy257/omE=,tag:91x3AKP7aqN719ksJmB8AA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-masterkey
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Fe7d52rguFUrVbdxsiEKrZa0XrzvPxyAb0qDBOqloCBTRETweFC3nAPMHPUefXVy/i9a1X/O/II2zeez/CpgV19CmgLVxJue2A==,iv:GozQe2QXfVWr52jXUvmyoY0/6PNRv+6FDGHruwN9J14=,tag:Obu8t9OSJ3/b6TX+0oEa2A==,type:comment]
    #ENC[AES256_GCM,data:3TF3gaCuaQA4/vrXijzPN6YY1lOG4pWFEV+yDiqEisNC6Y5nEVVvXuOcDTvGU+O8BIss0Sn5wURnt8o=,iv:TiQ06UrEP6uoNWX1Qjexxrpq4KZN5KmCn4dB5k/OPuE=,tag:KkLr0sNuFs7Ji5uwFTqV2A==,type:comment]
    masterkey: ENC[AES256_GCM,data:DjPZabkUm2hvqEwTOa/hFMiUaW25uFJR1NMGewYm6rY=,iv:ZavfXf7iYkfAKL/MPszp+Xl2fOR1oMA3WdiyCb8uUrA=,tag:zYPD4lGu+YUuZQ1q9v7lXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T22:22:16Z"
    mac: ENC[AES256_GCM,data:hyZ4D/e8o7VU7/ODLkgIEKF7kP5CFgX9TfDlOghJ5cagiMAtzOg1yl/sEruQHOwh63JbVsTkxr0VbSFJ6GIcBHLWpgdHLiYH05N+PA+Alpk6KmIENDe+wKIfAnA0oON9mvX9In+Btt0mXc62KKjB6RTaCZ9k1UIiqu+HMlQkPVc=,iv:9JkUgIFMrAW3SYTEBeh6Uvj6F/pviQYKRlVy257/omE=,tag:91x3AKP7aqN719ksJmB8AA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-postgres-auth
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:I56x/AH9kwqIKal4bQ1OiRUMOBPHpw==,iv:cIsiYS2rfyfwMoWO4zDefFG1j9ZO6yMtJDwSzI8HgQA=,tag:k9xjeEZy5nbLmOzk3Xt8Kg==,type:str]
    user-password: ENC[AES256_GCM,data:MtiUUxKFnDPFnNsCixARMmMmBrDdCKPe9A==,iv:LrI9VyxW5PCkDRMWoTvQYIcO61RMeuRLDCP0Ok2XG3Q=,tag:V/uIWijEAHwFoADow9ccDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T22:22:16Z"
    mac: ENC[AES256_GCM,data:hyZ4D/e8o7VU7/ODLkgIEKF7kP5CFgX9TfDlOghJ5cagiMAtzOg1yl/sEruQHOwh63JbVsTkxr0VbSFJ6GIcBHLWpgdHLiYH05N+PA+Alpk6KmIENDe+wKIfAnA0oON9mvX9In+Btt0mXc62KKjB6RTaCZ9k1UIiqu+HMlQkPVc=,iv:9JkUgIFMrAW3SYTEBeh6Uvj6F/pviQYKRlVy257/omE=,tag:91x3AKP7aqN719ksJmB8AA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
