# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:T7hlCVKY3ASiHHsIldTugt1NnJKL4T0khnwJSkX38VaiS36lpf2ijN0gB/MJoPuO1eJSfsbeTuwjIurE0/iPzfVPTGt3RpLa3Wrh4/U2Sf6Kr9OsY0qqKC2DvNpm20SNA4FGkSRN86K51OmZUbMXpKx3Um1apaYM0DZ0uXvYyTXZmnXE7HPTh6XeVeyPi6NzuP/yajnAPmOaxc/sMcsTIAt8UtrhzVRNWlc4E5MbFhM9ExrVTkKdHgBW9a2NzFhKHifTJSkXexei4FtPXifBlHE+MTKiEG9FWC/hyFyp3ixCnnHDdUkgZ0AdOwBWG2Sw7qJVWesEPjxBECA5lieNlJEQlbenijaw0XQArAddrnw0dtX27dyJ6TxsfxxGMt/4oXe/xSoGHVTwGxRmmeSexrC9ZWrEohBn5KlDNvFKx7Hxnou4zJtkojKo7zH5vHaYBJzv9pcLwlxztqQe0xZ+uEZFFENYwFrGt9MpyKyfdSLrr/yq8QsJKB0ocs0+cjqC73dbVdBCyXH1Y88ypcbyre5u+fA3iLhn2lJGiVhDcc5X3/3OH2RtTmuJTy55NMXnn0M5YusltzAbWhdbip3VqbRfTgmB3px5pzDFx/jPtPRWIQciN5oq1Z3233ekFvYHla5t7LheXoMcrFslcnzAYaO6CAGnkPBYfZDpmxWDx2niIab9m2mlo8g9PUmGyLLKNCKc/91ccW+hOFBTdBRRccL+WVgzj4Ilfvidl7OQXY9lF1EXGhzzr45WMD16LEFrOnMcYW4jevW+iYeRo7NtzV+bvBOXUNdUH0JcOcXVRykozHYx9lESgHFWvcJkKoEYeqg+qOTFAdBicaADvHQEWT6afoV0fP0PWOfVMtRVoEdQDc0PXexyoj7RC/nU4XI+1lmdDP8XCWh6cHMx4e+o/J75JPlBUMuowcB4w2H91Sc7,iv:29cRj5HsoXFycBff6HCkTWPQlchMV9Y+XNbqlOI/SOU=,tag:7+n0kC0ddZqKW4sdKUTVig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T21:05:44Z"
    mac: ENC[AES256_GCM,data:JwC9PVJ07s4qPKvWVlUCHLBUwxcVefe0zQYnOBV3VbR+Xy0sMVCsSwTb9go7yj2oGrQKHbKkFDsMxtBtbI/JCDFUW6ysyYCBC+TSbxq+/BInDurhleDF1pVuevsk9BGZsY20OYKy9f2XZB12uUlfT18LNgYW1HhSKU60wSjdhF0=,iv:c1NZu/BKF7F2mMR8RU5SHMGmr/uEy6wwY8DFfT4EzQk=,tag:E1J0bCVlLlVk9OMDg2VS8g==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-masterkey
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Fe7d52rguFUrVbdxsiEKrZa0XrzvPxyAb0qDBOqloCBTRETweFC3nAPMHPUefXVy/i9a1X/O/II2zeez/CpgV19CmgLVxJue2A==,iv:GozQe2QXfVWr52jXUvmyoY0/6PNRv+6FDGHruwN9J14=,tag:Obu8t9OSJ3/b6TX+0oEa2A==,type:comment]
    #ENC[AES256_GCM,data:3TF3gaCuaQA4/vrXijzPN6YY1lOG4pWFEV+yDiqEisNC6Y5nEVVvXuOcDTvGU+O8BIss0Sn5wURnt8o=,iv:TiQ06UrEP6uoNWX1Qjexxrpq4KZN5KmCn4dB5k/OPuE=,tag:KkLr0sNuFs7Ji5uwFTqV2A==,type:comment]
    masterkey: ENC[AES256_GCM,data:DjPZabkUm2hvqEwTOa/hFMiUaW25uFJR1NMGewYm6rY=,iv:ZavfXf7iYkfAKL/MPszp+Xl2fOR1oMA3WdiyCb8uUrA=,tag:zYPD4lGu+YUuZQ1q9v7lXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T21:05:44Z"
    mac: ENC[AES256_GCM,data:JwC9PVJ07s4qPKvWVlUCHLBUwxcVefe0zQYnOBV3VbR+Xy0sMVCsSwTb9go7yj2oGrQKHbKkFDsMxtBtbI/JCDFUW6ysyYCBC+TSbxq+/BInDurhleDF1pVuevsk9BGZsY20OYKy9f2XZB12uUlfT18LNgYW1HhSKU60wSjdhF0=,iv:c1NZu/BKF7F2mMR8RU5SHMGmr/uEy6wwY8DFfT4EzQk=,tag:E1J0bCVlLlVk9OMDg2VS8g==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-postgres-auth
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:I56x/AH9kwqIKal4bQ1OiRUMOBPHpw==,iv:cIsiYS2rfyfwMoWO4zDefFG1j9ZO6yMtJDwSzI8HgQA=,tag:k9xjeEZy5nbLmOzk3Xt8Kg==,type:str]
    user-password: ENC[AES256_GCM,data:MtiUUxKFnDPFnNsCixARMmMmBrDdCKPe9A==,iv:LrI9VyxW5PCkDRMWoTvQYIcO61RMeuRLDCP0Ok2XG3Q=,tag:V/uIWijEAHwFoADow9ccDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T21:05:44Z"
    mac: ENC[AES256_GCM,data:JwC9PVJ07s4qPKvWVlUCHLBUwxcVefe0zQYnOBV3VbR+Xy0sMVCsSwTb9go7yj2oGrQKHbKkFDsMxtBtbI/JCDFUW6ysyYCBC+TSbxq+/BInDurhleDF1pVuevsk9BGZsY20OYKy9f2XZB12uUlfT18LNgYW1HhSKU60wSjdhF0=,iv:c1NZu/BKF7F2mMR8RU5SHMGmr/uEy6wwY8DFfT4EzQk=,tag:E1J0bCVlLlVk9OMDg2VS8g==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
