# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:POllP3rzUf6499PzF8uDpLog0fdHZAeoV6X52anrzEeiX+PYSCiSO7/R07uEc6kWPGEpvO8R/rE5R8AxgbT4mOtHVgiFtFn5uQlQgUB/RsRr/GQQmVbFHaDlo3Pv3cXxsWXHzETdWL9Mc+LyMgRBaoqruuBGEZdtr5A8faknLYAwC2gfBoc77j9Ey0M75Uz7SsFd1C3BSyOPU1e7oEULL1hLqytH6MRjeIb0/UBjH1yOhj7LNvOPIxVTEHwV5lVnyhEStObsHGsvck0eFtZis8+gSnjRgOxmygYHfWb+FSldLWv2y/2XUEs5tkH2i2MwseWy3DMJ/lW6zbdVRW2v5A6X+gNpfBoJuGwaXWCvXXytN6BXaEhpNXEuUZOUhUXe676pHDskZYLrJR6UyYZOFjSjyqxHZ8iRcE91vyip1J+JsF3BopVg2BpOoHFGS3IIBwn1SjcydsPiYQYKtO6pRNbeBA/LhtjhZrP+BhGJ/b75r4GWU7uPA6G8a1fFCstaXYc0AuxNeCK11LpYrx3KfsrP/R6nJhQng8otvxIZtAuKECQPBRuF/TAbVjenaxKlDo/I8QzC8hzqLUYZkwcr7tvf7Lgo106xv8XcaxuJ5W06QK1Geen1+lFclF31Mc7lqiaBpWtlS+godP2X/1A3JTA87SXNhDo0uHm/8ujkHRZsZh/YRNJp1TjhncTK,iv:2jOLi5MTbczITBdZMN42e8ITkTgrOt3XudQQ/dMdUvM=,tag:G9fvSFXWbgoH0YP2ZnLaFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T21:01:03Z"
    mac: ENC[AES256_GCM,data:oE1p6jsiSZC9zNu1da7qQ1ApJc8Fn4OhLxc67+vCWq1bdl93EHIPa47mI/Q1OpSiIeEHdmydkbKHZh9pOhQSakQrk+ATb2+XZ58oinBJNHyClPq8rdd0DEMq2Sm3GiyfG2bQQtlGU5LnL3LhxYZf87IZAhk5rmKdXENrKsBNW6s=,iv:bI+Yi3PIwNwTnp0sdnLfMWOOupS8v2o9mzGV/Jti5w0=,tag:2OzPi7va6Hv+dHm3Y/gp6Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-masterkey
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Fe7d52rguFUrVbdxsiEKrZa0XrzvPxyAb0qDBOqloCBTRETweFC3nAPMHPUefXVy/i9a1X/O/II2zeez/CpgV19CmgLVxJue2A==,iv:GozQe2QXfVWr52jXUvmyoY0/6PNRv+6FDGHruwN9J14=,tag:Obu8t9OSJ3/b6TX+0oEa2A==,type:comment]
    #ENC[AES256_GCM,data:3TF3gaCuaQA4/vrXijzPN6YY1lOG4pWFEV+yDiqEisNC6Y5nEVVvXuOcDTvGU+O8BIss0Sn5wURnt8o=,iv:TiQ06UrEP6uoNWX1Qjexxrpq4KZN5KmCn4dB5k/OPuE=,tag:KkLr0sNuFs7Ji5uwFTqV2A==,type:comment]
    masterkey: ENC[AES256_GCM,data:DjPZabkUm2hvqEwTOa/hFMiUaW25uFJR1NMGewYm6rY=,iv:ZavfXf7iYkfAKL/MPszp+Xl2fOR1oMA3WdiyCb8uUrA=,tag:zYPD4lGu+YUuZQ1q9v7lXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T21:01:03Z"
    mac: ENC[AES256_GCM,data:oE1p6jsiSZC9zNu1da7qQ1ApJc8Fn4OhLxc67+vCWq1bdl93EHIPa47mI/Q1OpSiIeEHdmydkbKHZh9pOhQSakQrk+ATb2+XZ58oinBJNHyClPq8rdd0DEMq2Sm3GiyfG2bQQtlGU5LnL3LhxYZf87IZAhk5rmKdXENrKsBNW6s=,iv:bI+Yi3PIwNwTnp0sdnLfMWOOupS8v2o9mzGV/Jti5w0=,tag:2OzPi7va6Hv+dHm3Y/gp6Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: zitadel-postgres-auth
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:I56x/AH9kwqIKal4bQ1OiRUMOBPHpw==,iv:cIsiYS2rfyfwMoWO4zDefFG1j9ZO6yMtJDwSzI8HgQA=,tag:k9xjeEZy5nbLmOzk3Xt8Kg==,type:str]
    user-password: ENC[AES256_GCM,data:MtiUUxKFnDPFnNsCixARMmMmBrDdCKPe9A==,iv:LrI9VyxW5PCkDRMWoTvQYIcO61RMeuRLDCP0Ok2XG3Q=,tag:V/uIWijEAHwFoADow9ccDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T21:01:03Z"
    mac: ENC[AES256_GCM,data:oE1p6jsiSZC9zNu1da7qQ1ApJc8Fn4OhLxc67+vCWq1bdl93EHIPa47mI/Q1OpSiIeEHdmydkbKHZh9pOhQSakQrk+ATb2+XZ58oinBJNHyClPq8rdd0DEMq2Sm3GiyfG2bQQtlGU5LnL3LhxYZf87IZAhk5rmKdXENrKsBNW6s=,iv:bI+Yi3PIwNwTnp0sdnLfMWOOupS8v2o9mzGV/Jti5w0=,tag:2OzPi7va6Hv+dHm3Y/gp6Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
