---
db:
  postgres:
    host: "postgres-postgresql.infra-auth.svc.cluster.local"
    port: 5432
    database: "zitadel"
    ssl:
      mode: "disable"
    user:
      username: "zitadel"
      # Holt das User-Passwort sicher aus deinem Secret:
      existingSecret: "zitadel-postgres-auth"
      passwordKey: "user-password"
    admin:
      username: "postgres"
      # Holt das Admin-Passwort sicher aus deinem Secret:
      existingSecret: "zitadel-postgres-auth"
      passwordKey: "admin-password"

zitadel:
  masterkeySecretName: zitadel-masterkey
  configmapConfig:
    Database.Postgres.Host: "postgres-postgresql.infra-auth.svc.cluster.local"
    Database.Postgres.Port: 5432
    Database.Postgres.Database: "zitadel"
    ExternalDomain: auth.${CLUSTER_DOMAIN}
    ExternalSecure: true
    ExternalPort: 443
  configSecretName: zitadel-config
  configSecretKey: config.yaml

gateway:
  # HTTPRoute configuration for ZITADEL HTTP API traffic
  httpRoute:
    enabled: true
    hostnames:
      - 'auth.internal.${CLUSTER_DOMAIN}'
    parentRefs:
      - name: internal
        namespace: infra-gateway

login:
  gateway:
    # HTTPRoute configuration for the Login UI
    httpRoute:
      enabled: true
      hostnames:
        - auth.${CLUSTER_DOMAIN}
      parentRefs:
        - name: public
          namespace: infra-gateway
      # fix for cloudflare
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: "X-Forwarded-Proto"
                value: "https"
  pdb:
    enabled: true
    minAvailable: 1
  # metrics:
  #   enabled: false
  #   serviceMonitor:
  #     enabled: false

# metrics:
#   enabled: false
#   serviceMonitor:
#     enabled: false

postgresql:
  enabled: false

replicaCount: 2
