# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:U2jmTKqR+GkMovIVtLveyg==,iv:TlIAl72wdVzsK4eChJFu+rtBlP2RZnMZa1j9ma3Mj5A=,tag:LWQhzae7ZOpLfdcIYNNNbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T20:29:30Z"
    mac: ENC[AES256_GCM,data:5z8eQwT3nOYwc+xmsG5mGLpptKezgKSO0yY67QwOkQeqJUNvH1loyHgLePYp5jCQpw1gmNs9No0osr3Ub2Chw2dqEScz+2DRH/JsFClLhxJo5OsVdkqG2wnULgRJZR/2pDYzPzaJh1tn+uGkLRyHVQuup27+CimDJ/HY3YzxCfk=,iv:o1ZJBfBMJmIkKSKrOzA6pi4oKbsUe5MWiZk6lRIiFnQ=,tag:bJ2kRGorhSt+pHPBIXnbLQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
