# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: redis-secret
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:GDBIQzgo+7ZX5E/LY9DB15I9,iv:vR7NToSct4Ts8oaUa3qsNA90cQ6wVHtmeHPV2A6Q1DY=,tag:Fk9KBFaCCw5LhUBrOsXvEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T22:00:25Z"
    mac: ENC[AES256_GCM,data:UYQJFh9wZtn3iScQXnp7MCjkIShDLYuJRG1gSMnSK5X9lDiEoX5riiqnMUFZMQR0fcJDmhVjxwLta2vMyUvlW/ruIVQVWuPFZ3G2YvmwZcvx0d8YStSb6joG6ouyAmiE+xM3zo3mihsKH2Dp4KDq4ynWCrl/1Aws14Y8k/wfKMQ=,iv:83sMQOb/RfrB+hmrage8epz/lNbkqgQGiawicUP9JOk=,tag:hhp64AQJuiMoaG+4xRe3Ww==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
