apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/revog/my-k8s-homelab.git
        revision: main
        directories:
          - path: kubernetes/applications/*/*
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/source/targetRevision
        - /spec/syncPolicy
  template:
    metadata:
      name: '{{ .path.segments[2] }}-{{ .path.segments[3] }}'
      labels:
        category: '{{ .path.segments[2] }}'
      annotations:
        # Sync order:
        # 10 → infra
        # 20 → app
        argocd.argoproj.io/sync-wave: >-
          {{- if eq .path.segments[2] "infra" -}}
          10
          {{- else -}}
          20
          {{- end }}
    spec:
      project: default
      source:
        repoURL: https://github.com/revog/my-k8s-homelab.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        # SPECIAL CASE: Cilium must be deployed into the kube-system namespace.
        # It is bootstrapped early (Talos CNI) and later adopted by Argo CD.
        # All other applications follow the <category>-<app> namespace convention.
        namespace: >-
          {{- if and (eq .path.segments[2] "infra") (eq .path.segments[3] "cilium") -}}
          kube-system
          {{- else -}}
          {{ .path.segments[2] }}-{{ .path.segments[3] }}
          {{- end }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
