apiVersion: v1
kind: ConfigMap
metadata:
  name: vars-substitutor-plugin
  namespace: infra-argocd
data:
  configManagementPlugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: vars-substitutor
    spec:
      version: v1.0
      discover:
        # Search for yaml files in applications folder
        find:
          command: ["sh", "-c"]
          args: ["find . -maxdepth 2 -name '*.yaml'"]
      generate:
        command: ["sh", "-c"]
        args:
          - |
            # Template Helm chart (if existing) or use plain YAML and replace vars with effective values
            if [ -f "Chart.yaml" ]; then
              helm template . --include-crds | envsubst
            else
              cat *.yaml | envsubst
            fi
