apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: infra-argocd
spec:
  template:
    spec:
      containers:
        - name: vars-plugin
          image: alpine/helm:latest 
          command: [/var/run/argocd/argocd-cmp-server]
          envFrom:
            - secretRef:
                name: global-config
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-run-argocd
            - mountPath: /home/argocd/cmp-server/config/
              name: vars-substitutor
          # Install gettext if not in image
          lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", "apk add gettext"]
      volumes:
        - name: vars-substitutor
          configMap:
            name:  vars-substitutor-plugin
