---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-ui-private
  namespace: kube-system
spec:
  parentRefs:
    - name: private
      namespace: infra-tailscale # Explicitly points across namespaces to your Tailscale Gateway
  hostnames:
    - 'hubble.private.${CLUSTER_DOMAIN}'
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hubble-ui # The exact name of your existing Hubble Kubernetes service
          port: 80 # The service port of hubble-ui

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-ui-internal
  namespace: kube-system
spec:
  parentRefs:
    - name: internal
      namespace: infra-gateway
  hostnames:
    - 'hubble.internal.${CLUSTER_DOMAIN}'
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hubble-ui # The exact name of your existing Hubble Kubernetes service
          port: 80 # The service port of hubble-ui
