# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-certmgr-token
type: Opaque
stringData:
  #ENC[AES256_GCM,data:gcwtYVZ6dKSEDRVKoHu41jbd8uFz169UzZA=,iv:IZR9hw0AZiOw4uubGifmxB3QRPph8RKaj+JG1GBuTFc=,tag:/HDjToXfEmoc1mt9Kicspg==,type:comment]
  CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:yTvQil/ANZBB9a2Pa945FNGraEDqlpn/aiJ3p3F/dXQ4AqjnQIxZ5skNtUoExQeU2rTonWA=,iv:IlioVSNN7BoJFAWa5uaj4ZbIZN/tAuJC/WLAVzrdPAQ=,tag:XKyYjZVcNgGBl2oKwSKFiQ==,type:str]
  CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:UxXd5CW8dhOMryYp8PktsC3OjfY/N2rbkj6DIkj8G+4=,iv:xA26W6vjzLdfAOUZqvomSjiuoY9kE/JdCkvnMRfBxSE=,tag:QFes4EmPBnHwo4vjjNAY0Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
        L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
        a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
        UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
        nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-22T21:26:04Z"
  mac: ENC[AES256_GCM,data:6OSfSqyOlFow8OXAeXrr7ntZuiXCGsVNaD2/Uzj80AkFJfxnghA0arwLjiGNih4g2FzfE89x1KaMx0WaKkdFA6dfr/IgSxHgyMNvrprSdIUp05wNUKjut+vGV6RQuvO1JGS02TI/0uwoXTprRtU37kAEikI8vVZYDUc3l59vcI8=,iv:9SAXMNHLDRxLW4yh28Rnr4H/zZufuD3XR+YzJKq3vDE=,tag:5SMbNJOaCKj0wWQAVjNH/w==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
