# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: infra-flux
spec:
  interval: 12h
  url: oci://quay.io/jetstack/charts/cert-manager
  ref:
    tag: "v1.20.2"   # choose a current stable version
