# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/referencegrant_v1
---
apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: allow-tailscale-gateway-to-read-wildcard
  namespace: infra-certmanager
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: infra-tailscale
  to:
    - group: ""
      kind: Secret
      name: private-wildcard-tls

# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/referencegrant_v1
---
apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: allow-internal-gateway-to-read-wildcard
  namespace: infra-certmanager
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: infra-gateway
  to:
    - group: ""
      kind: Secret
      name: internal-wildcard-tls
