workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PAPERLESS_PORT: "{{ .Values.service.main.ports.main.targetPort }}"
            PAPERLESS_DATA_DIR: "/data/"
            PAPERLESS_CONSUMPTION_DIR: "/consume/"
            PAPERLESS_MEDIA_ROOT: "/media/"
            PAPERLESS_URL: "https://paperless.internal.${CLUSTER_DOMAIN}"
            PAPERLESS_ALLOWED_HOSTS="https://paperless.internal.${CLUSTER_DOMAIN},https://paperless.internal.${CLUSTER_DOMAIN}"
            PAPERLESS_CORS_ALLOWED_HOSTS="https://paperless.internal.${CLUSTER_DOMAIN},https://paperless.internal.${CLUSTER_DOMAIN}"
            PAPERLESS_ADMIN_USER: "admin"
            PAPERLESS_ADMIN_PASSWORD: "changeme"
            PAPERLESS_ADMIN_MAIL: "admin@admin.com"
            PAPERLESS_OCR_LANGUAGE: "deu"
            PAPERLESS_OCR_LANGUAGES: "eng fra deu spa ita"
            PAPERLESS_CONSUMER_POLLING: 120
            PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
            PAPERLESS_LOGOUT_REDIRECT_URL: "https://auth.$CLUSTER_DOMAIN}/logout"
 
