# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-secrets
  namespace: infra-flux
spec:
  interval: 12h
  url: oci://ghcr.io/external-secrets/charts/external-secrets
  ref:
    tag: "0.10.0"
