# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: webdav-secret
type: Opaque
stringData:
    WEBDAV_PASSWORD: ENC[AES256_GCM,data:xGGG9ZKLqYPspmBIJD73,iv:kDsic3r7Hx9E9qG6B/xP8MsTjHfcr4RJ0iZ2Qe+ETvI=,tag:eE9D4GQXevOSMFcZartlQA==,type:str]
    WEBDAV_USERNAME: ENC[AES256_GCM,data:9PP45gx3YXq5,iv:s9XjYRKwgoD8VxsUZ9B5iA2eyebNsvsRE9T6GiFiHFo=,tag:yb1TTGb6UDMmcQEOPUKy8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T19:59:17Z"
    mac: ENC[AES256_GCM,data:AnbYXALUw8j5g10ZrBJz7tDQF7Dl+keL2XRUu+MaIRFMpKb+kr680rpG4KtYIuTJT+dVfnDCSFJgR0l8AB8VUcdZ0hL2TkDZmY9xLe2BLdP1L83OeeDmBzKDQCWcRcMAcCl6GgaYmLqj/gaIy1r3kdA2jw3VYD1Mm2eFQnyGbJI=,iv:B90cQZ4qE+qJZNqUjlutY+cK/1EQqRTSKeVwlke6c1U=,tag:OkNGWrpcns8wbPIjuC0hCQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
