---
controllers:
  main:
    annotations:
      secret.reloader.stakater.org/reload: "webdav-secret"
    containers:
      main:
        image:
          repository: sfuhrm/docker-nginx-webdav
          tag: "v1.3.0"
          pullPolicy: IfNotPresent
        env:
          AUTH_TYPE: "Digest"
          USERNAME:
            valueFrom:
              secretKeyRef:
                name: webdav-secret
                key: WEBDAV_USERNAME
          PASSWORD:
            valueFrom:
              secretKeyRef:
                name: webdav-secret
                key: WEBDAV_PASSWORD
          PORT: 8080
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false # Nginx need write permission for temp cache
          capabilities:
            drop:
              - ALL
    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001 # Enforce Kubernetes, modifying file permissions in pvc to gid

persistence:
  consume:
    type: persistentVolumeClaim
    existingClaim: paperless-ngx-consume
    globalMounts:
      - path: /media/data

route:
  app:
    hostnames:
      - paperless-webdav.internal.${CLUSTER_DOMAIN}
      - paperless-webdav.private.${CLUSTER_DOMAIN}
    parentRefs:
      - name: internal
        namespace: infra-gateway
      - name: private
        namespace: infra-tailscale
    rules:
      - backendRefs:
          - identifier: main
            port: 8080

service:
  main:
    controller: main
    ports:
      http:
        port: 80
