---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: infra-flux
data:
  CLUSTER_CONTROLPLANE_VIP: 192.168.100.50
  CLUSTER_LB_EXT_GATEWAY_API: 192.168.100.61
  CLUSTER_LB_INT_GATEWAY_API: 192.168.100.62
  CLUSTER_LB_PRV_GATEWAY_API: 192.168.100.63
  CLUSTER_LB_POOL_START: 192.168.100.61
  CLUSTER_LB_POOL_END: 192.168.100.80
  CLUSTER_NAME: homelab
  CLUSTER_TIMEZONE: Europe/Zurich
