apiVersion: v1
kind: Secret
metadata:
  name: cluster-secret
  namespace: infra-flux
type: Opaque
stringData:
  CLUSTER_NAME: ENC[AES256_GCM,data:+qai/1Uv/g==,iv:HghX5m0w7abS0iKDxmz5HbkptmclK8LBhZOlNTGJyII=,tag:QoPqrBWnCZ5TN/eGhGa6sA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMHdBZFd4NXhONVNFV21l
        RHJVSDh1YjdLend1V3V5am12SzNGR28yMTNZCnEvNkw5T1BycGZkN1o2U3Qxditv
        bVZJV2VEWTdsZXljYjExMFR6d2NYRk0KLS0tICtPb1puaklIRElVZkhjU3dad3Nl
        dmZDcTZxZzEzSUxXemwrSTdOb2srQWcK1Fgo6nB3nwO4ZYK6hSdC3BQa13X3+iIb
        Oye2Nt25/htHf466Wj74uidKB9UCijHfBi7I2QVgm6TICUduxwj5Dw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T19:49:01Z"
  mac: ENC[AES256_GCM,data:7mApJg+FQ9cwCnLS9bpZXLfTEHAppiZa9dAfbt7fl+L5YgZECDneCBDWc0I37QqUJEmwJ3qTxJIP3Py0xejx3/ce2xVMdvQ3hsknziM77qHTy/hoejIFDdY1VPOTVDuZcKEzx5HZLU0DQJYsy4P6icB3If1LEgQBwK0PxyVpjv8=,iv:uZk/Jo9+kXfZY9uatSXtEs8GoqjGvKl1AHiqFjA0lFc=,tag:1uuZZepuSISd+j71/fTCbg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
