apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret
    namespace: infra-flux
type: Opaque
stringData:
    GOOGLE_SM_PROJECT_ID: ENC[AES256_GCM,data:Eps1uf3pjPwScuADevSmoQ==,iv:WyPf0sXgm4IgwmPT+CHnj/8EkAkuHoDJRqWyA4ZdYys=,tag:sx7Yx5M30Sq4gDEX+whwKw==,type:str]
    GOOGLE_SM_LOCATION: ENC[AES256_GCM,data:HsxQlIcZ6wZRNyYk,iv:kIOXjc6impZyeohm6LHl8nY09ShpzqoUM6CxD1nIWAc=,tag:VOrT6kdYwARYjDyt/qrBSg==,type:str]
    PRIVATE_EMAIL: ENC[AES256_GCM,data:WarZlpNFDVat5MIjHg==,iv:+ZcJI57bVKR8yR7GfR/noXdHvApMB4wdk9UScrKNgyI=,tag:b3eOTSEbjAfeW+jVrXWdvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMHdBZFd4NXhONVNFV21l
            RHJVSDh1YjdLend1V3V5am12SzNGR28yMTNZCnEvNkw5T1BycGZkN1o2U3Qxditv
            bVZJV2VEWTdsZXljYjExMFR6d2NYRk0KLS0tICtPb1puaklIRElVZkhjU3dad3Nl
            dmZDcTZxZzEzSUxXemwrSTdOb2srQWcK1Fgo6nB3nwO4ZYK6hSdC3BQa13X3+iIb
            Oye2Nt25/htHf466Wj74uidKB9UCijHfBi7I2QVgm6TICUduxwj5Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T21:37:07Z"
    mac: ENC[AES256_GCM,data:sXvM2MObdiTGOp2DcRqWqtGQeH1bnaiKZjd5SdWXL6sUnz+YOFrxraphAH1KxhzR5b2Xnlgf74YsfHKAlTvk8OjCSV8zh4eCbtIoLeiPMsIG7slKjNhcGE0AcD94T3O8h4LP6lWUTWxif65irXvvd+pXVzgbjJqUDWZNaqcN/qE=,iv:XOoxHahzO8gTZkbUI1QQ/RG6zYSwHdbb4bfpfGB+MNk=,tag:wKAL4sBuue4VLgH3oILapg==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
