---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: infra-flux
data:
  CLUSTER_POD_CIDR: 10.244.0.0/16
  CLUSTER_SERVICE_CIDR: 10.96.0.0/12
  CLUSTER_CONTROLPLANE_VIP: 192.168.100.50
  CLUSTER_LB_EXT_GATEWAY_API: 192.168.100.61
  CLUSTER_LB_INT_GATEWAY_API: 192.168.100.62
  CLUSTER_LB_PRV_GATEWAY_API: 192.168.100.63
  CLUSTER_LB_MQTT: 192.168.100.64
  CLUSTER_LB_MUSICASSISTANT: 192.168.100.65
  CLUSTER_LB_POOL_START: 192.168.100.61
  CLUSTER_LB_POOL_END: 192.168.100.80
  CLUSTER_NAME: homelab
  CLUSTER_TIMEZONE: Europe/Zurich
  HOMENET_CIDR: 192.168.100.0/24
  SLZB_IP: 192.168.100.11
  STORAGE_IP: 192.168.100.100
