apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: infra-flux
data:
  CLUSTER_NAME: ENC[AES256_GCM,data:gpNeGMNMPA==,iv:FlohKJUMXsPHZoiuWIuqca20cN0i09H3Ox4W6aBu1ng=,tag:KJMdc5CuHWsARavIYlY8wQ==,type:str]
  CLUSTER_TIMEZONE: ENC[AES256_GCM,data:vxG14ZBNOQwLg7DXqQ==,iv:v9nDY7NZsQG2SK49G8Z0nhCi/V74J9HL9uzApTSYMY4=,tag:IEqilo4FcqtrQ0MJSofX3g==,type:str]
  CLUSTER_CONTROLPLANE_VIP: ENC[AES256_GCM,data:Ung7BVl4zYYpt3tz2Ns=,iv:WYMZbBM8zr5KHgclFZvlTTMx0i0B8sqDlF7fceCrvBk=,tag:nIFg587CLNM2oI+smKi0fA==,type:str]
  CLUSTER_SUB_DOMAIN: ENC[AES256_GCM,data:EYlkUA==,iv:1RQMVWWreRo4dbVdB07Iz/7rryno4pnO8KNLuYIJtqs=,tag:3U7pgxRh7YuWsWymk2XrTA==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:6lKYPONPn3fONYg=,iv:45yPRCS7RUZmJN8OuF5Lp4t6tQMsw8rMnwI3UdMcDJM=,tag:ok9CdcvqX1btiKuychxxfQ==,type:str]
  GOOGLE_PROJECT_ID: ENC[AES256_GCM,data:3Ru8CGl0aCQnAXZVGmDfbw==,iv:yl6DSM0jOz9bcebozaS/Ch3f6lBovJ12nSoBQBb5Whk=,tag:Un5BocEaoDiC6vDEpZE3qA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHRqODg5K1Zm
        dnpxQUFRaE9EYloxcmRaUlJ3RUZIUU1MRUtudDdQaFRDK1phd3FwRU9Ea2lobW9v
        eC9EWjhNWlBadFRMOStmY3N3aTI3L21IdTNNV0JMaG44dDVWNHk1RWFJYVdmRkRn
        Zm5IVnA4VVhOSXJHL0VLOEVUMjZkL1EyQlpCV0hwS1ZVUStiajcrbzlQZExPRUZu
        YzQxendkdGczUEVHNG8wOUJNdWh0dG1tZVhWQXBvdmdCRVVqbDNGeGV0SjJjZWJp
        ZFhBSGFhTVlvcDF4UDVTM1E1d0JGS0NOTDh5Y0RzOC9keWpTMkVybzg4TktGalZQ
        WWpjWmdtWTVueFdYWFNsdi85NUtVU3Vkb1ByUWpHamswZk0xNkg2UjZYU3dsdVZX
        TnJZTXI1ejBmMDkxcUZiRmo3bGZoRmg0QkFTODBEVk9oNVkxOC9YNUladTY0eDZE
        TmRTNWpkSFJMVFNVeHIrcmZlbWNINnRReFdYZkc4enVSMFBmbXNQSC9qWFZCSnNj
        SEIxOTVHNkdRMDRIZ2l0VFl2TlVLRTFhRkVjOCsvZDNpZ091VkIrUnRvTDVMNFhQ
        d0pob1JxWHlwalJTYmlPeldSQUYyU2IrZ2ZMWFlWUW00d3UvL1V0T0pGc0hLWTVE
        WHhreEZ4cmM4RVlJQmRJTWkvdmJpR25HcW9NRlZIZWFYRU94bjZrekdVRHNaQzFL
        eWdpb2RxTkJVRUlxZEQ2bThKVGM3MHlab24wT1loRGQzN0lydGZHOGlpZGpKL2tR
        a0JxMEhlNzVuVUNqY0dOQkZIZnluS09IbUNId3pIRVhPUDk2UkxNMlpXZDBTQVFX
        WHdPTWNESldROWtBNnRQVFk5TTVEK2I1Ny81VWpadmhjbEhHbVJTd0dybHlJK3dN
        dWx0NFpqbGx6ay9Yb3VhQ2ZHdFZoY1drSXlQNUNYQnpJaHQxcmNSVHNiekJxL0t5
        Q3hHZDNhalYrdG9VZFkvMXNRMUNZYTNEcVVOWEJLRW00a1ZSc3hBeVRNZ0xZaVhO
        WUlsOFArOWRqQ0txVDBya0Z6eDlneGgzeUtYVTJ5aWl4QWdRMWxTdEFLTWFsY0ly
        dzhYU0pJQnRvV2pXSjZYK0VlcFNwWWdaVUYxZXRSQStIN2U0Y0NtMnUrWmRxZ044
        amtDQ0M2TjR1WjhVbHdDS09UZ1FxMmcrdm5yU01PeFdSdGJ5RURiMHJTZHoycTJt
        NktFMnU5T0dIRVMvSTNOMFIwanBIZDhiNWdkTVhGdG5Xb2RnNmR4U3ZGN3cwWVpN
        RVNkRjd1K0NXRUV1bDFuQ3JvcmswMXFXWjNaZjY4Y2ViNEM2N1J3anJ3MVN5aXJ1
        WU9qdWtBckJMbUxqVWtLRURucmtoTUUrZEs2MU4xekExcFhkdXR2Y3JKaVZ6d3lM
        Sy9tdzRxbG9hc3dKbWI4dmUvSElqcHpBekQ1dVF2eVQxZlhLeFlnOHljMFc3TGll
        NzZ6S01ZWXp3M1dFeW1ma0ozM0VyQzRCSDFWMi9GSUxMSmt6c2lpc1NLTHd6ZFJW
        aFl2SEhuRy9FODNZU0lZNTM4Z2pGT0VpUkVKL3N6eXBqZ2N3cURUNk5tU0M3UjRK
        RVo1Tkw5QUhRTHhoUzU1T2N3cnVJWnJBQlZzWjdMdHUzanp2aEZMcDZGSVhaQ3hO
        cDFmTk1TNjJLNXlUQXBZOWFmTTlPeUhTRndRKzhBdzJqTzE4eXFIYXhjUElLZkVZ
        YWZOYlFOQ0xLa0VRVVB0SFNXRTZCTm8wUmlobDdkeHBqYWNPa2xUbmJRcG1mMmNh
        a2hnSjhnQiswd0JOcWFNcnlYK3kyWDhkanBBS1RLemdOcGRrMnpCYnJYbVZlSE5u
        akRPRit2L3FpWHZQSHpraHhLLy9KaHBWelduTlFncXFGSlpsZEpnRUlEV3FsMHV4
        RjVLRGM1QXlqSDBKTXlkY1IwMXBhd2NyYUZ3bC80UXdRcjJxVjcvVkFDMVZJdwpL
        b2N3Wjk5Z3VwU3dRVGtkQ2VKZ2gzOHFLeVRMZkVPeEp4QkVRenhKbjFnCi0tLSBw
        aFNwVndra1ljbldHNE1FQ3UvWk1DWitkbkN1STczNnR5Z0VFZDBsa1ljCnM1GUlH
        98xQKqeQwxVF+mWLAT8KKyiGv+7ciNt56XE29+QZZ/qf8l491kB0szPzCazXiVSI
        jxvYUWIzhJy9uns=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1ama2fj0rynqwnnz9jxlxe6max4jyevnh5c30dd0xedn27efsfzrsh6dkvgy22cq8n3xvc3mhmar24clryfteqz4dvfwg2wgexl6qz4fqvqquq5egc44vh7dr28pty7x6jt43tylzwxxur5eys828683yqc6lclpsjuz62jx8qecvtlj2ffgefwm99yps5qe9k5t5xws6hdzvkwtczdg2dzu9sggsnggnxwkmqy4hgyaqgyefffcz870k3wmj8wfcnw5eevryvlsh54qu8s4kv7rymtzz4a2uxjkpw54s55zr8pwx32ygkksxvlusfdkkh68k3gh39gj7dgm5flrc7lrm5ln3gswcc222vg6zu7u9fhc8ppk4hsdptjslyv2tycqnwwp9happrd3cv4u2m4wzsm6hxhdzzgy3f29qm3r09qaqkvsrfpsppg385h3eg2p9q723mnp5zh0zksfr0qlm54gnhv2s8ct9u7qrta2ngczequr2qa6xxk2j0z0nnfyw4zrvqxl9pxg6wgs4am6j4avvezfwyup34j5yzcmhfjlrfkvtg2ccjy25jnr07mx8emt3rt2p2nkpzqxvkny9zdpc7l7xeqdyj27trpfvvzfrp0s2sgepzushhd469xvpt4ck6st679ft03tm3thr9znrcwqndx9j39ns2wlhwmanxy58zfu3f3r3dt65wdwxkraeldrq5yqpl8mk22jsge2dygr2wx0vmjmjgn4myw25z8pq3qk9uvwklvug6m3taz74d387k3w9z74fpzmxl5egpehuydg2dtcs4vjm329vgcvnmnsh2g9d4dtl9g8fw5ukx6mf6xp9pxdl9wapqp2z75mhcsuzh23khhdgjuh09yamemyjqxfqvymu8c7a3xk4hj4l4fpg26f2ug7qryfh5s8y243tuey6myvsxnu6r830xcusrwf9n2dnejys7rxe84fudy2zvh8582jff5ts9yfg5uw6xxatyy9kxq5crmfesjx8nltjg940nqwkx5vm3rc8gfq8v4yz2ggqv5zyxfgcgqcy8xe69wx0dty0pg2requ7qncjyzu93hvy3zx92pp6u3fqcu79usxhslz2qkd2aqntwppv9l6m5x39k4d05hw8vqm8nvk882np5d84hfg6kj6tnvvv59p7rlg33h6ftsqndzuzhsm7m2987z7tevzsngs8ft8pmqy3a8yks4ace8c5xhykkw09zeuet7nr3c6g4l2rrg2q54ueq22cr3vcxhgxkhe602gh8jfgevm8yhyarp5yhmkvwswefdz5f230yqe8ujg57486vearjrjfzdfuzsnk26wvdp9u43saep4ggsdqgvr8gs4yttr5eudpkxwehguu3d3us5wzgsevgp45q04rgx00p5n05fd5ku5xtavvzkerqkzj87am89qmmr9qp9znjp08gp00gpu8h4f3knve5ln3x0yr5p07ws9l88z50mhh3dl3qcskcyj6meyxwk9qgwhn0hc9kepm6p7trd3eezfhd0zshdnnwmrjrj3kt6dz7gvep3u8py86ykzrf38va2gpskzkdfm22mj65xd2mgu5tnrqswc8gg7ezmax5ev7gzpca6wqervgq6xyqp0tq6t3cds8gvjn4l64ea34n58wqcjmzxu84p6qed2fvd6n59cre3re0g95k5934vqkgtzgrc97tnehas3tafdge2jx0zau5a2mq7nrmv0pngcc7y22mdng33ztg2n5wawfrs34cdnc6eekdsdjjehqc7tk0audk66pe2w8gw49whsmxx7ntfgax3msra0xj6djk3mepspapsw0t43csa3mq8wr8clzjm4nuwjdnydwm0qenxm63y74hd29ry5wkxw6mknug633gnnr2mm4qumu7nu2vvn909jv03m2ne5rvz698cfu2z5y
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T20:44:35Z"
  mac: ENC[AES256_GCM,data:nA8yPMg9Yj8IGzrZWYHaShrEjaM7IVb76nfhEn/07JhCtmAEflEcPONBBvVhipm90jEf8bkmSXCzlttXY7InmvBoLCZ3Ge8/qU1VjxYo/6Wvss16Xtppg1JiNHnXilX9Wh/6MGLry16iO1g4mMSWPzukZ3KZ2jZ/AIhYKFys8N4=,iv:mk98Ykz3WMPoa0vANngwwAWo7gr8rubbN/e+DIQhnl4=,tag:WUSvFJBg8zIJL0sFXkT3mg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
