apiVersion: v1
kind: Secret
metadata:
    name: cluster-secret
    namespace: infra-flux
type: Opaque
stringData:
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:cxAGSxDUxyrBtdCONY/xoO1RzkwNHA6nUbDVNjvmTuo=,iv:/QzZOmVVPZ549qGac01VU9J58xN9KNIMUV6IgOS63Gw=,tag:67+MoBLkmHvJ62iOaRrZ6A==,type:str]
    CLOUDFLARE_API_TOKEN_CERTS: ENC[AES256_GCM,data:Rt82M+Pq7EIaik8MtfAlAugSSIcNZign3Aj4l9MMZDq/mHGMm3ThSR8CcVUpPmstMZIYLCY=,iv:0mlNkkpkg5rXSHf4FJUHV996XM0pgLMnwgwTwqMYQbs=,tag:0+BmO//d/0D0SUyS5lX6Uw==,type:str]
    CLOUDFLARE_API_TOKEN_DNS: ENC[AES256_GCM,data:nntllzkn3YqNMN06gjeO3AICz8uNIHCAIaluIidB6O8ohe5T0qAo+3K2wbwxdpdUGMhdeL4=,iv:k1i2/HLdMAnc3not6QwdCubMJN56Dgn3zZWh5FZBp3Y=,tag:j72A6qxW+umvErPClHSnOw==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:oFMgDB4vq8zfuBv6yg==,iv:m7Q0cbBVqan6JGtytXOye0OZNUtlCCC0bDNPW+ny/fE=,tag:l9F075Eadj3q1isz/zxdIQ==,type:str]
    GOOGLE_SM_PROJECT_ID: ENC[AES256_GCM,data:Eps1uf3pjPwScuADevSmoQ==,iv:WyPf0sXgm4IgwmPT+CHnj/8EkAkuHoDJRqWyA4ZdYys=,tag:sx7Yx5M30Sq4gDEX+whwKw==,type:str]
    GOOGLE_SM_LOCATION: ENC[AES256_GCM,data:HsxQlIcZ6wZRNyYk,iv:kIOXjc6impZyeohm6LHl8nY09ShpzqoUM6CxD1nIWAc=,tag:VOrT6kdYwARYjDyt/qrBSg==,type:str]
    GRAFANA_AUTH_GENERIC_CLIENT_ID: ENC[AES256_GCM,data:QKJsb9RxLMwdGt319tNnlkAtAIk=,iv:tHicel5M4Wrf7AHW30xCDJYzNJVfIjzOOp5I2qM92Hg=,tag:yQy9aGtPDZ+xF1efycAcQw==,type:str]
    GRAFANA_AUTH_GENERIC_CLIENT_SECRET: ENC[AES256_GCM,data:B8wh0W9cT5NeGrpem1v+9IP8TMkha4jgpI2e7YWRf7BoGtpMEJN5QS++a7hDVcJBSUBWy+fg/b72GUBtfmaMNA==,iv:XmiYEbpNvp2zWM7q+2E3QHemFPBW/CmB7TWLaGuuvtc=,tag:y1j3Y3kbF2wW+JrbKHADWA==,type:str]
    GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:jWyHDf4=,iv:Zw2jpWB2/KBbKn6i/bSgoNTYC9KjVJ9rLnbWJgt7hWg=,tag:k2dgh7JBHdSmZMzhyJ7Zng==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:o7ex8+zTb40nJ7SOLYwhs/BNsJCMxMM1,iv:gTY4TN4gAyaQBibm9+TPFGN9mhMVNg8PZLCvbLViNgM=,tag:qy4SaSV8YfcrQjefq9KTtQ==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:QVkvUhs=,iv:/AseDh8acpyDBjK20utLQOZDhO7GgX2o/hguj16Vdio=,tag:ZcucrSmHaeoc1hL+f6ibQg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:xMY4fYPuYNxUss2UOqAmPe72OClDJpI=,iv:nTl8M+JHxv9D+M0elpPLu+1zdvjYcLHbSj+f9UtpOco=,tag:9MrhBQCyei2Oa/9jG3QRug==,type:str]
    PRIVATE_EMAIL: ENC[AES256_GCM,data:WarZlpNFDVat5MIjHg==,iv:+ZcJI57bVKR8yR7GfR/noXdHvApMB4wdk9UScrKNgyI=,tag:b3eOTSEbjAfeW+jVrXWdvA==,type:str]
    TAILSCALE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:JTiAwbCOwY3Q6uiwL+CyC08=,iv:RAEeiem43TNd6x6K+V8L3LEJVaaty/cVbv1pT3pTF7k=,tag:f8iG/q5t5uuOJ4N2SrUKdQ==,type:str]
    TAILSCALE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:3DdSfuOH1ymDl0N3WTDL7xxMYdQiwNKkS46EklPyWGJoRmNa2G8J7if0mbiTDuI4Zzxg5BEV/PVcmByEWPTf,iv:+S26nKZ53D+QdsjF28N8na7+kbKlpQi8Ao5njoEQmw8=,tag:1cNaP+1sElbDUQvig8P/zA==,type:str]
    VOLSYNC_CLOUDFLARE_S3_ACCESS_KEY: ENC[AES256_GCM,data:0GBN8xOPQcMjzRne2hn4N9ursORQZ/friUbyXM2PoRU=,iv:lPKcSwc8ifnUL4/09SG4JUZl1OVh9U9EdLJdkL1QlGw=,tag:RD5rar3SgcUpwTBoKQI2Bg==,type:str]
    VOLSYNC_CLOUDFLARE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Y2iwMkRCAmilAxO4hO5jZwT/ODbdqc/jwhz2jJXNlsA3A6Yp/FWb2Opp9SOOInlIY6wUo+IEv6excrw4y87RXQ==,iv:iWzl38zsj6WdDBt63XJHosBY8u4lXBAWyk44CbimvmU=,tag:H+7vOEgw5DhjjP24k3e3ew==,type:str]
    VOLSYNC_KOPIA_PASSWORD: ENC[AES256_GCM,data:oyBnnETuNTVPDehgi/+CtNnuqKSMn6MP,iv:vFIPwxuWR7Au9aLSFekJRar2vi8IKXa1y/k4c93KyKM=,tag:AGe3vtyr4dED9ky8fWHXUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMHdBZFd4NXhONVNFV21l
            RHJVSDh1YjdLend1V3V5am12SzNGR28yMTNZCnEvNkw5T1BycGZkN1o2U3Qxditv
            bVZJV2VEWTdsZXljYjExMFR6d2NYRk0KLS0tICtPb1puaklIRElVZkhjU3dad3Nl
            dmZDcTZxZzEzSUxXemwrSTdOb2srQWcK1Fgo6nB3nwO4ZYK6hSdC3BQa13X3+iIb
            Oye2Nt25/htHf466Wj74uidKB9UCijHfBi7I2QVgm6TICUduxwj5Dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T21:10:26Z"
    mac: ENC[AES256_GCM,data:tYzZI4BgbNtfcm0KnhpGKVZYd5bPizKYVMIVzxYky3OJ/dSSZM9vIiSo21KF+89kj6Rm68R95p44WamTqzIMLmodhajRKiCI6jOI5G1S+3FdBHe5i1g7SHAJAd4QUTsznd2DsBViJv/i8uGdxyhy4SzmQXC96762p8al+CSK9/0=,iv:P9by4xbix8fo5JzybgPBsLbf5GmcGYzM8ZeF43qf5nA=,tag:BdK6/pZ2TtyI5DXk2L34/g==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
