apiVersion: v1
kind: Secret
metadata:
  name: global-config
  namespace: infra-argocd
type: Opaque
stringData:
  MY_DOMAIN: example.com
  CLUSTER_NAME: homelab
sops:
  encrypted_regex: '^(stringData)$'
  age:
    - recipient: age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
