apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
spec:
  interval: 30m

  chartRef:
    kind: OCIRepository
    name: cloudflared
    namespace: infra-flux

  valuesFrom:
    - kind: ConfigMap
      name: cloudflared-values
      valuesKey: values.yaml
