# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
metadata:
  name: cloudflare-tunnel-creds
data:
  credentials.json: ENC[AES256_GCM,data:XIPREcGirDipc/ozJUuIGxm5G+GO/rxkg+7Sa9EeLn08wlSqc5g4DiFyKP4Ad5KZETa7p6RM3/W0wQ/K568rKeGf/h+zggYmxLaesFeURz64QWedeYp6qcQiYzyYErA9rEdBy4cyPu4bW+cUxodBlOWEf53CUOgNtxihR8r6+yl1FVYZe+yf4wdCaBQcGvfiN8uAx1/+deBeeI9O/jiYV0076evkgcLt+fmFqwUyvdrHZ6R2TOeziRKlUU8E/rd7jHr30kGlv2xzM2A6wFYixPqyZTkT/iaE8ZFM2zaNmLXsfykAvuxV6Afu/i8=,iv:se5OmwM4xqFpaAcz3iAdeSfW03W7j/ep4aGIXnZfGhY=,tag:MN3+N/sPyEB5T8hxC2zqjA==,type:str]
kind: Secret
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacCs0MXdRTHc3RlFZbWpM
        TW5WLyswK3FMZmZXYllYT3M2K0N0SjVuUmtFCnFqODZFYWc1VElRZ1ZobVNKUS81
        cjhYN2VBWWtUVnB3Mk5SQ3U5QmZXL00KLS0tIFdEMndTU1BiNUFtdUJmTkZCTG9T
        TjhRM2VOMGRJcEVTVGZrYlBtMTlnK3cK3/XW1mWCDPA5zRn3WpKQIDpHy0wEGAkc
        D0TL7AUbsAmOuMrNKDTxYk1h73nYwmfoas8MkREI38gCWIm39/FZqQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-22T21:33:23Z"
  mac: ENC[AES256_GCM,data:3FMCamHpDg2SieRGAiAGTf/8sv3OVvxLNyMUPB94SlP68dbbvgbwUJO3LH6nxuPyEkbcw2O05x/QxNvUzuIomjjvHfmWweTtmd72wtsgpiD+7AZHLZJ+EqoALyQ8mUqbUGkj8vnvs3V6pGiNh+1/uuJA2M08eD5S3kK+Z16IUxQ=,iv:7n0ECmcCFeq/gnY1AcxBi64JXUfTMYhBKgePql/kukI=,tag:djGFMRq/E8nKcVSvMko8tw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
