# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
metadata:
    name: cloudflare-tunnel-creds
data:
    token: ENC[AES256_GCM,data:k/U3bSnoLOYHLxOwHLsX4+Fn3LMBpwGiKX3SOZw2TeA67Zfxa0lPud88Vede0JWhADBK+LMFOdSBx2rwjTD231NXGF5440ITxY+MqbUefRPuMohmteNKUTj81bUNyfB6Qp9QjR2BP7Kdod8Yhu9FFczu/yKwhHwA5kQVMtMgU/tT04GVrdGQgoGoFd1h5EcyKxYX/AmUOIOjsqyaKllDfvsLNB022k0Gn3omEAd20sF7uU6wugc6FA==,iv:jc+tuSWJJwXrDW2r8OU7tIWKOsZnnV/FBNm+ctYyhm0=,tag:/o2m2lA2+DJ5y3UadHyXOQ==,type:str]
kind: Secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacCs0MXdRTHc3RlFZbWpM
            TW5WLyswK3FMZmZXYllYT3M2K0N0SjVuUmtFCnFqODZFYWc1VElRZ1ZobVNKUS81
            cjhYN2VBWWtUVnB3Mk5SQ3U5QmZXL00KLS0tIFdEMndTU1BiNUFtdUJmTkZCTG9T
            TjhRM2VOMGRJcEVTVGZrYlBtMTlnK3cK3/XW1mWCDPA5zRn3WpKQIDpHy0wEGAkc
            D0TL7AUbsAmOuMrNKDTxYk1h73nYwmfoas8MkREI38gCWIm39/FZqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T19:56:36Z"
    mac: ENC[AES256_GCM,data:hPh3kQ0Qq+V91MwN8kf/nJNGlRgd+OrqCSh1m0TEPWJMbgNbBilp2fot2NCYUsoJgddHHSCkIMo9hT/JStoKlOhPN3WMqDHFpQovtgbKGQBeY2nd9bRvZl+oS775VFpwGAcvDDOslnB34TQ6UB+vTPLzyxnOXPElbqCUzd3ho2E=,iv:aUTLKmIM4Wyl6MRW5nNSE0fqEvQzfh+9RRFcqTo6eNc=,tag:/8J/BzHZqwp6ABk94lww0w==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
