# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
metadata:
    name: cloudflare-tunnel-creds
data:
    credentials.json: ENC[AES256_GCM,data:0I/AzPBQT6dLr6V4ICL3vHtGE1ZMK/SzLo3S50K7v+21VGvLN/6rF8l2LVdnfoY/8rkt6u/1kTLu7lUom09TpJGa8f6ldkeByUOw1SdBACFvCm9GflDK4feo4eVrvpThuvH0dnFI7FyiPMSYwoW49ZHIBno4V/0dIEunCCtlyI+M0LBvQsG7l4GbtmlGdI5yEKgmgFvH8a497hegYLQ5aAMMJkTl1vJz12XeF86bxPHKYljVyPTofw3VGaqWnoEvTXwm3Uoe9oyuYf2lQwmKDDjrvNaWHGTKv7kPReV2OMF0rfaQY1ZxK3v2hRw=,iv:yutSxzRJ1+MGhjQI3Er6M3LWHoYVzFlujn16IF+H4m0=,tag:l7HrS7cy0mbJKMEGPsAOvA==,type:str]
kind: Secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGtCR0hzWXN4
            MjJFK0laOUZ2amtyMWxlandLbEMyZnN2eXh5NkppTkpmMjlpRjVPS2p6YmwvOHNX
            Q2tYQkJOcHdtQVNxaUIrMDA0NGZpRHNoTnZUeEI0ZlZCZ2tGbit1WFYxVnVoejdY
            T0lQaUQ2NFczYUJCajhtM3FLT05yOHJuVzNqek05Qm5JaVNkcTZCNGVSQmFoVklv
            TUdEb3RWSW5kRG8xaVp6V3FJcDFPVzNUQm9aSnFyT3NPckFmZkg0c0N6cVdpangz
            V3lmY1orVURlMzcxbTMySm5weWRFTGVrYTMwaTNuckh5anN4ajNzeDdzcEIzOHBn
            YmZ3OFVGQ2ZSSWMzRTF6VzJXQXlRbFh6d2dadkZXcHQwQmxZTDNwY1BtVkVrRzBn
            Vy8yNEJDWWFzS1hwYVM2S3Vsdjc5V000QWtHL05BQnhVTDlJWWVGYkxlNXJvMnhp
            Zy9QWVhKRDEwaUU5TUtGM2taQzdUUlFISGFzN1Z1ZUYrbmxEVFFGZENnY3J3a21G
            eEM2YjgxekxlNGtjRW96eTV6cG50RUNCM1JQcWk3cU14b2NlZE9vV0h6MzBKaTF5
            T2pSUEpoMFB1OERzU3M1aTU2OE5aZnhYbG10a1hYeFl0emIxVmRYWUJWckYyZFYx
            WnZNYUM4UTRKdjBsMzFUcWRlQTQzRDZKUzZzZERVeEFPaGtEdEVHRGx5Tk5TZVJF
            TVR5L2t3bVV4T3g0WjBnUkw3S04rb0dMS09BdEJZdXVUSWJ1a08vb2JVOTUzRWxy
            R3lKRmw1ekdBcmNXOWYvazRVeTFacjhRTGlrL2JleFh1dDZ5STRJdUVScnNqRUhn
            NVBHTFJmZVl0TDQxbmprTFNUamxDZmpSYVR3SnNyVDFEbElxdktWYnlnbVFib0F3
            U25GTDY5MXJWb1hQa3dnOGFzS0tTWDFkalFGM3dpaFlKdUtUdEd1VGxSVHp0WVQy
            dFlaeDQ3clVSQXgvYWREV0RRbnJYMUpmZG5NSThGSERlQlR6L1lwR1JjSW9QaFRT
            bTlhTEZyUXgranNJS0UyNUl0QkNOT3RhQWk3cGhsR0dKV0E5a1c3c2Y4U2NqbitR
            RXpmZjVEN1lxUmpJK3h2azlwZkdKSzU4MHJnTHkvNHNiclVuYkxKd0w2czBMWkVI
            VDB4WXdaREVuY21KWC9yTzE1N3ZNQnUvVUhWSGdnTjFEWTM2eVlqWGRWeWtVa2xr
            NXhIblR0ZnNVcTRNSTQrd2Z2OGtKVnQ5VVN6NW8weXI1SEZIdVdQWGRHNU1wTzhm
            K0NnQjVOdk9OR2hSSEJpaE9tdE0zYVJzeU01NU9PajJCaG1FUEVjc3ZKb3o0TWRy
            R0dBeDlFTEEvdmliT1NMR3hoRnRteGFjdTJIN0JPSXBEWnE0RU40ZE56MU5EckJn
            NUZZdnVyL0dlOEtnbFNrYjFMZFQ2UElDQ01kVDhCeGluaEtickgzQXUrQ1FtdENs
            R0VtTXNmdFFHTGpYelVuRUE0aGZJSUlkVWtKRnZxSjJKTmdnMUJweVZncHVmSmRL
            RkRqVmx6RjdGYTVDZ0FEc3MyeTNBNjhjaSsrY1JkTzJKRzBWZG4ydTRFenNsaHdx
            OW42WmN2bEZyTTdKVDA0RzZEL1NpRW5UVm03RmU5WEZzaStBUnZNSlVWdnN5Z1ZU
            eW40S2VLQVlFUVZYVjYrbXVNMm5odmhSVHMvWFJVV3kxWC9nZEZlRzlNY1JGTDlI
            Y3YzVVdPaW42c2YrZmtUZTNtajVSL29sRWtGaFZEUS9xWTVOcVNMQTRxSVcvQkNz
            Q3p4ME9NYlpUQjJISUdNSHgzMS9EejVRb3AyTSsvSnRzM055dUxIaHZKOTh4cDZ1
            MWF3dEh3bkZKSmNPSEYrcE9NT2tEdmk5RlVaZEFCLzZtbGcwdnZ3OUJnbEFCdTVm
            ZnlWNHpUYkw4eUxHWVA3M2lwM2dyVEFmR3FyeUFDTklqWjltWmlrc0RoR2ZQdwpR
            M3A2aVpaME05VWdBVi9rSVpTOW9LUW5qVHZ3c1haQ2lTckp2dVBkOTRvCi0tLSBD
            U1AyQVMwcTBvU1htbnpUZGNnTlgxdmtEM0FXZ2lhSmkvN2F3QW1TUmtJCrR66XrN
            yO4EYR0ZhuFLH5mFFhYcnENGG6LNlt1qxEsP+1/kHCpZf5eulRSaY1CdX3mGytHw
            hv9lUT3zsWYfd10=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1ama2fj0rynqwnnz9jxlxe6max4jyevnh5c30dd0xedn27efsfzrsh6dkvgy22cq8n3xvc3mhmar24clryfteqz4dvfwg2wgexl6qz4fqvqquq5egc44vh7dr28pty7x6jt43tylzwxxur5eys828683yqc6lclpsjuz62jx8qecvtlj2ffgefwm99yps5qe9k5t5xws6hdzvkwtczdg2dzu9sggsnggnxwkmqy4hgyaqgyefffcz870k3wmj8wfcnw5eevryvlsh54qu8s4kv7rymtzz4a2uxjkpw54s55zr8pwx32ygkksxvlusfdkkh68k3gh39gj7dgm5flrc7lrm5ln3gswcc222vg6zu7u9fhc8ppk4hsdptjslyv2tycqnwwp9happrd3cv4u2m4wzsm6hxhdzzgy3f29qm3r09qaqkvsrfpsppg385h3eg2p9q723mnp5zh0zksfr0qlm54gnhv2s8ct9u7qrta2ngczequr2qa6xxk2j0z0nnfyw4zrvqxl9pxg6wgs4am6j4avvezfwyup34j5yzcmhfjlrfkvtg2ccjy25jnr07mx8emt3rt2p2nkpzqxvkny9zdpc7l7xeqdyj27trpfvvzfrp0s2sgepzushhd469xvpt4ck6st679ft03tm3thr9znrcwqndx9j39ns2wlhwmanxy58zfu3f3r3dt65wdwxkraeldrq5yqpl8mk22jsge2dygr2wx0vmjmjgn4myw25z8pq3qk9uvwklvug6m3taz74d387k3w9z74fpzmxl5egpehuydg2dtcs4vjm329vgcvnmnsh2g9d4dtl9g8fw5ukx6mf6xp9pxdl9wapqp2z75mhcsuzh23khhdgjuh09yamemyjqxfqvymu8c7a3xk4hj4l4fpg26f2ug7qryfh5s8y243tuey6myvsxnu6r830xcusrwf9n2dnejys7rxe84fudy2zvh8582jff5ts9yfg5uw6xxatyy9kxq5crmfesjx8nltjg940nqwkx5vm3rc8gfq8v4yz2ggqv5zyxfgcgqcy8xe69wx0dty0pg2requ7qncjyzu93hvy3zx92pp6u3fqcu79usxhslz2qkd2aqntwppv9l6m5x39k4d05hw8vqm8nvk882np5d84hfg6kj6tnvvv59p7rlg33h6ftsqndzuzhsm7m2987z7tevzsngs8ft8pmqy3a8yks4ace8c5xhykkw09zeuet7nr3c6g4l2rrg2q54ueq22cr3vcxhgxkhe602gh8jfgevm8yhyarp5yhmkvwswefdz5f230yqe8ujg57486vearjrjfzdfuzsnk26wvdp9u43saep4ggsdqgvr8gs4yttr5eudpkxwehguu3d3us5wzgsevgp45q04rgx00p5n05fd5ku5xtavvzkerqkzj87am89qmmr9qp9znjp08gp00gpu8h4f3knve5ln3x0yr5p07ws9l88z50mhh3dl3qcskcyj6meyxwk9qgwhn0hc9kepm6p7trd3eezfhd0zshdnnwmrjrj3kt6dz7gvep3u8py86ykzrf38va2gpskzkdfm22mj65xd2mgu5tnrqswc8gg7ezmax5ev7gzpca6wqervgq6xyqp0tq6t3cds8gvjn4l64ea34n58wqcjmzxu84p6qed2fvd6n59cre3re0g95k5934vqkgtzgrc97tnehas3tafdge2jx0zau5a2mq7nrmv0pngcc7y22mdng33ztg2n5wawfrs34cdnc6eekdsdjjehqc7tk0audk66pe2w8gw49whsmxx7ntfgax3msra0xj6djk3mepspapsw0t43csa3mq8wr8clzjm4nuwjdnydwm0qenxm63y74hd29ry5wkxw6mknug633gnnr2mm4qumu7nu2vvn909jv03m2ne5rvz698cfu2z5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T19:02:51Z"
    mac: ENC[AES256_GCM,data:aPmF/IfR7OtUR/Zml/bG1c4Vw6IDCKAOGmJ0mC1kN207g76S56+hQmqHnxxZzQWw/1WgpQEQXCsqnskeEU+9yI8vRtDMi3bTdamNu1vakrDAIvA4aO+5MlpOKYS3fCZ+uDBpdquvfRKZrswL7HNf/vJQYx7BUP89Icr0JyJLsaw=,iv:JqSeHGcShwimut0t+ZaErP+pKwBD2pKD7fIU8OEbGMo=,tag:m3u0FmGSfkLpr93/EwhydQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
