cloudflare:
  tunnelName: homelab-public
  tunnelId: ${CLOUDFLARED_TUNNEL_ID}
  secretName: tunnel-credentials
  ingress:
    - hostname: "*.${CLUSTER_DOMAIN}"
      service: "http://public.kube-system.svc.cluster.local:80"
      originRequest:
        noTLSVerify: true

replicaCount: 2
