---
metrics:
  enabled: true

pdb:
  enabled: true
  minAvailable: 1

replicaCount: 2

serviceMonitor:
  enabled: true
  interval: 30s
  labels:
    prometheus: kube-prometheus

tunnel:
  existingSecret: cloudflare-tunnel-creds
  existingSecretKey: credentials.json
