---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pocketid
  namespace: infra-flux
spec:
  path: ./kubernetes/applications/infra/auth/pocketid
  targetNamespace: infra-auth
  interval: 15m
  retryInterval: 1m
  timeout: 3m
  prune: true
  wait: true
  dependsOn:
    - name: longhorn
  sourceRef:
    kind: GitRepository
    name: homelab
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: pocketid-data-pocketid-0
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_SCHEDULE: "0 */4 * * *" # every 4 hour
      VOLSYNC_S3_SCHEDULE: "15 */4 * * *" # every 4 hour
      VOLSYNC_UID: "1000"
      VOLSYNC_GID: "1000"

# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: authentik
#   namespace: infra-flux
# spec:
#   path: ./kubernetes/applications/infra/auth/authentik
#   targetNamespace: infra-auth
#   interval: 15m
#   retryInterval: 1m
#   timeout: 3m
#   prune: true
#   wait: true
#   dependsOn:
#     - name: storage
#   sourceRef:
#     kind: GitRepository
#     name: homelab
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age

# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: zitadel
#   namespace: infra-flux
# spec:
#   path: ./kubernetes/applications/infra/auth/zitadel
#   targetNamespace: infra-auth
#   interval: 15m
#   retryInterval: 1m
#   timeout: 3m
#   prune: true
#   wait: true
#   dependsOn:
#     - name: longhorn
#   sourceRef:
#     kind: GitRepository
#     name: homelab
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-age
