# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-auth
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:GzUvrHmmepxoM7yPRpr7H3C8peMoF2wv,iv:2isvEx1Kzod5jpLgITmrydLWrbDfrrBg7eDIAM8Dr9I=,tag:+5fDGpIObzzNvMmfUbfPJA==,type:str]
    user-password: ENC[AES256_GCM,data:dRp17Wv7xh1HjpHlpaWDqjn3Wjx/43Atoug74g==,iv:HKYwxxWyxKfO59nukzmwtPFL6QxlN35Skfe+XojQmQM=,tag:VwzQJdwr2Qay+ZoTBMzQvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T14:47:33Z"
    mac: ENC[AES256_GCM,data:btFQcwPK/tUrxNamasmw2uMGd9hkY6AcsAWPlZGPFK4ZkARFpbeY2tqa1u2AtFL3vnjInq+F1arQOf0oFJCUQ4z1RxYOY2O3U6u2fPQt6a6SpGZRHGafMsgysyabaC+/zzhFt0KnegVq0Tj019xRWxW0dkupXTyjoyv65cXeBo8=,iv:sb1n4Ce4B91UhazL0wPgeQG8IcAvw50roKSncGm9EFA=,tag:b1ypVWyR4clpJo+5QMAxtA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
