---
auth:
  enablePostgresUser: true
  existingSecret: "immich-postgres-auth"
  secretKeys:
    adminPasswordKey: "admin-password"
    userPasswordKey: "user-password"
  database: "immich"
  username: "immich"
primary:
  persistence:
    enabled: true
    storageClass: longhorn-v2
    accessModes: ["ReadWriteOnce"]
    size: 4Gi
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
