---
auth:
  enablePostgresUser: true
  existingSecret: immich-postgres-auth
  secretKeys:
    adminPasswordKey: admin-password
    userPasswordKey: user-password
  database: immich
  username: immich

primary:
  persistence:
    enabled: true
    labels:
      volsync.backube/backup: "true"
    storageClass: longhorn-v2
    accessModes: ["ReadWriteOnce"]
    size: 4Gi
    dataSource:
      apiGroup: volsync.backube
      kind: ReplicationDestination
      name: immich-postgres-bootstrap
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi

volumePermissions:
  enabled: true
