# Global settings
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

per_listener_settings true

# Listener 1: External traffic (password protected))
listener 1883 0.0.0.0
password_file /mosquitto/config/passwd
allow_anonymous false

# Listener 2: Internal cluster traffic (anonymous)
listener 1884 0.0.0.0
allow_anonymous true
