# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth
type: Opaque
stringData:
  AUTHENTIK_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:cmAMzM4AaevAWjLG9BPFwDZq1izZROh6CQ==,iv:eiLV47vf5EZJXAa3tsO3/ELKOpyVgcqy8PHNrNpKGzQ=,tag:T46O23puM8a3Pbn5iG3Jig==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
        TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
        Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
        VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
        hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-10T20:32:24Z"
  mac: ENC[AES256_GCM,data:VhXSJG/yUnOW8qieMEbI0TSpt+w7MN4adlcA2eGcR33F4hl1TNg3AhkAODZ8H9tyBK1Y6FpW6ox7Wg8/YAct9+Lz+IvEeZe4LDCVTSbivkbVp5v+du1s2ncT39RY69wbkqiQSktCIkdc4XnHfsTByW0yFdbaZ9pIINapQO21600=,iv:/20wsHvbbjcnQS/wcgGFO1/U7R34bjYYEtTDNjJBNXQ=,tag:w2Yl6GVBK2rZ8+P6T2+/1A==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
