# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
type: Opaque
stringData:
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:U6rEc1xseM7aumVJHBP4VXvqkY6gwUlUgg==,iv:eTnanZYcflrHlBfyBrRV/yamp6cmXu8RYhk/l/3elFA=,tag:/6xIIBfIxp7rKgyOg2mo0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVVYRjdyTk8vS25WRnlG
            TGZDclR6Z2RCbzBSaUpCallHejNDVDJVTURrCmRCQ0MyZUlmYzVxY2x4MUxEU01P
            Sjk0bC92RzIya25QZTdIMEhNYUFud0UKLS0tIG5oTlh3RDNpM2p5YzQ1d1ZrRmdI
            VnJkd3FhZU9LdWtNRHpjTFBDaHFTRzQKaWTxTwrjX0i4RFwsT6jc2QcwHIII2Wvk
            hMtxHKD8ZI1kgD8IfP0PO8m75/+vpdXfiofFgKZ5nJO/qG0h3ywxyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T20:43:21Z"
    mac: ENC[AES256_GCM,data:25dL59AN+8g81BbRKSc9sNpbI6sKkzqCpJxDAtfwPU8kQbA7HQfw3kwV+Ql1rJ4YXb9/6yychnhq7fqlHV8FnOx3k/0iW5j8sfo4unEG3YGKD6+iwlq1EfojU3/xpogwxlNOc2B80+f7Lv1eVbGP6EeueED+majpRo5FnPsjhoo=,iv:VWuYLhvD8yRIjrnHAoCSLjFBO0NFmXUzhsuNSwzCPiU=,tag:A+Gkfl4izWCxDOnvgNBowg==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
