authentik:
  env:
    - name: AUTHENTIK_ALLOWED_HOSTS
      value: "auth.internal.${CLUSTER_DOMAIN},auth.private.${CLUSTER_DOMAIN},auth.${CLUSTER_DOMAIN}"
    - name: AUTHENTIK_LISTEN__PROXY_HEADERS
      value: "true"
    - name: AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS
      value: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12"
  error_reporting:
    enabled: false
  secret_key: ${AUTHENTIK_SECRET_KEY}

global:
  envFrom:
    - secretRef:
        name: postgres-auth

server:
  route:
    internal:
      enabled: true
      https: true
      hostnames:
        - 'auth.internal.${CLUSTER_DOMAIN}'
      parentRefs:
        - name: internal
          namespace: infra-gateway
    private:
      enabled: true
      https: true
      hostnames:
        - 'auth.private.${CLUSTER_DOMAIN}'
      parentRefs:
        - name: private
          namespace: infra-tailscale  # Explicitly points across namespaces to your Tailscale Gateway
    public:
      enabled: true
      https: true
      hostnames:
        - 'auth.${CLUSTER_DOMAIN}'
      parentRefs:
        - name: public
          namespace: infra-gateway
      additionalRules:
        # Force the Gateway to inject the HTTPS protocol scheme header. This ensures Authentik upgrades its internal WebSocket engine from 'ws' to 'wss',
        # preventing browser-side Mixed Content blocks (Interceptor errors) when accessed via Cloudflare Tunnels or proxies on port 80.
        - backendRefs:
            - group: ''
              kind: Service
              name: authentik-server # Erzeugt die korrekte Service-Bindung
              port: 80
              weight: 1
          filters:
            - type: RequestHeaderModifier
              requestHeaderModifier:
                set:
                  - name: "X-Forwarded-Proto"
                    value: "https"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

worker:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: longhorn-v2
      accessModes: ["ReadWriteOnce"]
      size: 8Gi
  auth:
    enablePostgresUser: false
    existingSecret: postgres-auth
    secretKeys:
      userPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD

redis:
  enabled: true
