authentik:
  secret_key: "b7cRP2xLm9Qk3Zr68YtN5Szgh6aBhD4uH1E0GqMZyV"
  error_reporting:
    enabled: false

global:
  envFrom:
    - secretRef:
        name: postgres-auth

server:
  route:
    main:
      enabled: true
      hostnames:
        - 'auth.private.${CLUSTER_DOMAIN}'
        # - 'auth.${CLUSTER_DOMAIN}'
      parentRefs:
        - name: private
          namespace: infra-tailscale  # Explicitly points across namespaces to your Tailscale Gateway
        # - name: public
        #   namespace: infra-gateway
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

worker:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      accessModes: ["ReadWriteOnce"]
      size: 8Gi
  auth:
    enablePostgresUser: false
    existingSecret: postgres-auth
    secretKeys:
      userPasswordKey: AUTHENTIK_POSTGRESQL_PASSWORD

redis:
  enabled: true
