# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kustomize-mutating-webhook
  namespace: infra-flux
spec:
  interval: 12h
  url: oci://ghcr.io/xunholy/charts/kustomize-mutating-webhook
  ref:
    tag: 0.11.0
