cdi:
  staticPath: /run/cdi
  dynamicPath: /run/cdi

enableDRAExtendedResources: true

kubeletPlugin:
  extraArgs:
    - "--shared-dev-num"
    - "4"
  healthMonitoring:
    enabled: false
  nodeSelector:
    feature.node.kubernetes.io/pci-0300_8086.present: "true"  # 0300 = Graphics Class, 8086 = Intel Vendor ID
  privileged: true

nodeFeatureRules:
  enabled: true
