# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex
  namespace: infra-flux
spec:
  path: ./kubernetes/applications/apps/plex/server
  targetNamespace: app-plex
  interval: 15m
  retryInterval: 1m
  timeout: 3m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      # APP: *app
      # VOLSYNC_CLAIM: immich-library
      # VOLSYNC_CAPACITY: 250Gi
      # VOLSYNC_SCHEDULE: "30 2 * * *" # 2:30am
      # VOLSYNC_S3_SCHEDULE: "0 1 * * *" # 1:00am
      PLEX_LBIP: "1.2.3.4"
      VOLSYNC_UID: "1004"
      VOLSYNC_GID: "1004"
