# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:P9Y6wGc2X/SJqi6B/GrLAPFO7OnZwhUVvEtn5TQUeQMj,iv:tNWCeuDnkqQW9gKUObsBnzqMzpHe/gqEey1B/XeCXMI=,tag:OIWMQ24oDULYzG3Wms8M6Q==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:si90US9VQMRoN3MgV9Ykz7HLDb072n9zgSSvfQ+jRxafOkfannhrkmwjrLM//03dMm+YFm4dXQziOvUkqMY5+0or1nzGuLr1,iv:t4T976tlB6uhi19MwFd9J28KoozBWiL29aF/JZYs3v0=,tag:zsSqOAhlGz2b3xyGpzE1ug==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:M8GYtk4=,iv:U3QsEYhx5lX1zysCFlKZsrekpmMbDqTH5zke1tofNcQ=,tag:5LDmQmM3qj0uNXcK2Vry3Q==,type:int]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:WDxK6JCxU0jaIo8=,iv:QHN2wuTqU307ygavhZNvY1J82a8vdAu886JTNdN1SEQ=,tag:MT5Fex08yOEeaqSlx39t8Q==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:OTukLCeLAyyouN385A==,iv:sLQKAAKctefUi5svPbUZiLvGGbBOkOBNYMGCHTqPjuQ=,tag:NnOjpYasgS2Cb/Rp6jrmrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T13:12:35Z"
    mac: ENC[AES256_GCM,data:iN1aCxP3MOJ2QD4jHbqd4FrdCNCSRpCFcoC/wZ5lKcRPdRsTEnBKA3QLGq4zNFDbqJ+y8E3ULYRcRLtxsshWWl0NxdPat5Q68daYOyIKgDflnU0ZqPn1e+n+fIrQkgdG3+rqlHNT9ljNb+ZV8GnU+1wnUvAHQPMKpjHMThs6crc=,iv:+QPVppx1aG5Zpvr6z2DTqLvbFbUapmjMeIZ1CmYJm/I=,tag:aRNQIx+T+ib9eZkOPnwMew==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
