# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:gi/sMzA=,iv:AG6BFmsHX3V7Ub6aVZWF/xdE6/uOENih5gqOMIQzXt0=,tag:xb/1QlaWjYNdRY8uO6nzJw==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:BvZfJJOi5mNHemdhyOXjAELpTJil9Hg=,iv:FqXWyO6UHVAQJEEPAy/YLpGYSPgrAV8RSarlTao5bL8=,tag:jZDWfeyAGBaf0pboSgAoKQ==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:c9vgQBmA0nqe8XCFVLZ/z6Pzijj7+sEfHMZTXg7F22I=,iv:s2anmrsn//KQ1QJdeKmwZJViBJy/yVFmiCxfSAX/HmQ=,tag:LMeh3cXdN1PBPcHwNMsI0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T20:31:53Z"
    mac: ENC[AES256_GCM,data:klAxKCIg2M3lFTyPZC/6h2nT3dvDKs2XCd6HvA5mRGw5/GR+BbVt7P6dWna7usJPUHkBgrLFKirYEAcYjz5ztd05WRAloNX1Poi5w08aIcpA79+aphkFbidUCf3yVsPiJhEe217BY+BRYQ8RY6uBrH40ji16tUgQcwPU+gs6nNI=,iv:zRmTPFRPH3bOUZ6EsFnJrU9pgPqwhAofav9h/hG017I=,tag:yZFXFIJbqfRYC6WfWty2aw==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
