# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:q2WGDBfdiUUzoUQ+0OopUEvl9kfuj1pd,iv:QVP4Npg0EW6iXTIToR8s7ocaUVAnEqvCEdU+tIxAiug=,tag:SCq0oPlSBExLUmq8m0A9zg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnL3FNWkdqdEN0WTFpdUZH
            Lzc2bnJOOHU1VTlLRUl0Wnp2dk5sTmtudmdVCjh6NFMvN3NsLzJ2VTlmRHdXQ3pK
            SjBZOERsZ0o1bUp4UDlJM0I0Qi90VTgKLS0tIDkvMkc5MEx0cTJEQlZsamVxajRL
            Z05vZDExV0xxZ3F2NE5NMW9GWWNRQncKKf/zI/eoMDVO8Ycl/hFrpRyelSqfqZ7F
            APRHrxPhy8KbzPff980IpME6T78BLfA1zhNm1v1xZEJkWIWgSDIPwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T15:29:43Z"
    mac: ENC[AES256_GCM,data:8n7OYaOIVsjpmn51K6VOHdfeZWO3HWeufLE7IoTIbvU5B92vgkWbq6Ck3VjIYTE1bnCMeXBj38u7JOQa8HgBtSeUkti0CcKK5sKJTBFhRRqdwFu5od+VKxKycqr88UTBuNHTTIv2bSrwtbiYdcf0MTakAdjrnXg2iOg0neZo/Zk=,iv:stz3x9HQhOuETjxYx42CGEmO4MIadRBQaEtCVjRZjno=,tag:ofn6aQqCeBUIj+kd3+4BFQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
