# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: <TBD>    
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbE9vaGg2ZXRWcnZISFQx
            L0VuMkVxbE1GZitocUJhUDJmZXhDZURhcWpZCk1IN3RTbmxTTyt3MTJ5bTRnclZy
            a0JqbmgvWHQ4b3hJYzhtdXhNU2tCYTgKLS0tIFpBRjZTbnFkblM0NUNIK1dlVzZs
            UWpTSi9zL05FWVprQ1I2WFQ0K1h4ZkUK7kNew0Pbwg6L7DOdE4vClkyPToGn6gIR
            nSXWPNcR1Mr572EO6dFCqTYQhGL09oMP0gdWbcvH55y15/aZrYDOLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tghcyt0d6vsqfmyqxh8pyyn43swn2v9knftf75h8d8d62dhy0slq7txntc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T19:21:21Z"
    mac: ENC[AES256_GCM,data:NqGvoABY4xJkg8Aqv8VqRGlNEIMruE6PKCO7sJ6SEl3N5ko29XtIFnA7e+oihWOyHmmI/IWV2+QKqtvR9eeBcfJVcMNhWKcApQs6fuAeGil6JZBVsqTeUUyg60TjUXgj22n7JojpTlBIc5TgmIA2mCCdesQh6zVuKv4yVYw9hm8=,iv:JVwRqKOuXr5ySmPbr/adN+0TT1NvihY/ngti0YGZa3A=,tag:gxGosi8D+JojEz6VALBTWA==,type:str]
    mac_only_encrypted: true
    version: 3.13.0
